### ISSUE TITLE
Support for resource type PodDisruptionBudget

### ISSUE THREAD

**Issue by mojsha** [fabric8io/fabric8-maven-plugin#1047]
### Description

Trying to use the PodDisruptionBudget resource fails, even when placed in the raw folder.

### Info

* f-m-p version : 3.5.28
* Maven version (`mvn -v`) : 3.3.9

* Kubernetes / OpenShift setup and version : OpenShift 3.6
* If it's a bug, how to reproduce :
Try to create a resource of kind PodDisruptionBudget, e.g.

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  generation: 1
  name: demo-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      project: demo
      provider: fabric8

Output:

Caused by: java.lang.IllegalArgumentException: No resource type found for kind:PodDisruptionBudget
 at [Source: N/A; line: -1, column: -1]
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3530)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3449)
        at io.fabric8.maven.core.util.KubernetesResourceUtil.getResource(KubernetesResourceUtil.java:181)
        at io.fabric8.maven.core.util.KubernetesResourceUtil.readResourceFragmentsFrom(KubernetesResourceUtil.java:154)
        at io.fabric8.maven.plugin.mojo.build.ResourceMojo.readResourceFragments(ResourceMojo.java:597)
        at io.fabric8.maven.plugin.mojo.build.ResourceMojo.addProfiledResourcesFromSubirectories(ResourceMojo.java:502)
        at io.fabric8.maven.plugin.mojo.build.ResourceMojo.generateResources(ResourceMojo.java:460)
        at io.fabric8.maven.plugin.mojo.build.ResourceMojo.executeInternal(ResourceMojo.java:264)
        at io.fabric8.maven.plugin.mojo.AbstractFabric8Mojo.execute(AbstractFabric8Mojo.java:74)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No resource type found for kind:PodDisruptionBudget
 at [Source: N/A; line: -1, column: -1]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:255)
        at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:981)
        at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:56)
        at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:31)
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3525)
        ... 30 more

**Comment by nicolaferraro** [comment]
I did not know about this resource but it looks very interesting and useful.

Unfortunately it seems not to be supported by the kubernetes client. Could you open a (related) issue in the [kubernetes-client](https://github.com/fabric8io/kubernetes-client) project, to add support for it?

**Comment by mojsha** [comment]
@nicolaferraro Done.

**Comment by evoxmusic** [comment]
@mojsha is it available into the latest version ? 2.6.3 ?

**Comment by rohanKanojia** [comment]
Will try to prioritize this. Since an issue is already open in client, closing this as this would be automatically fixed via next upgrade to kubernetes client
