### ISSUE TITLE
 Invalid proxy server configuration for secure Proxies in companies

### ISSUE THREAD

**Issue by amoAHCP** [fabric8io/fabric8-maven-plugin#1059]
I'm running minishift on a company laptop, configured with a http(s) proxy. The configuration needed to run minishift was like this:

HTTP_PROXY=$USER:$PWD@$URL:8080 & HTTPs_PROXY=$USER:$PWD@$URL:8080

When I try to depoy a project using fabric8-maven-plugin (3.5.31) I get following exception:

[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.31:deploy (default-cli) on project party: Invalid proxy server configuration: unknown protoco
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.31:deploy (default-cli) on project party: Inv
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)                                                                      
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)                                                                      
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)                                                                      
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)                                             
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)                                              
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)                                
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)                                                              
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)                                                                                       
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)                                                                                       
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)                                                                                         
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)                                                                                             
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)                                                                                              
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)                                                                                                
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                          
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                        
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                
        at java.lang.reflect.Method.invoke(Method.java:498)                                                                                                     
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)                                                                  
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)                                                                          
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)                                                                
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)                                                                            
Caused by: org.apache.maven.plugin.MojoExecutionException: Invalid proxy server configuration                                                                   
        at io.fabric8.maven.core.util.KubernetesResourceUtil.handleKubernetesClientException(KubernetesResourceUtil.java:523)                                   
        at io.fabric8.maven.plugin.mojo.build.ApplyMojo.executeInternal(ApplyMojo.java:393)                                                                     
        at io.fabric8.maven.plugin.mojo.AbstractFabric8Mojo.execute(AbstractFabric8Mojo.java:74)                                                                
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)                                                    
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)                                                                      
        ... 20 more                                                                                                                                             
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Invalid proxy server configuration                                                           
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:144)                                                        
        at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:55)                                                                                   
        at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:125)                                                        
        at io.fabric8.maven.core.access.ClusterAccess.createKubernetesClient(ClusterAccess.java:60)                                                             
        at io.fabric8.maven.core.access.ClusterAccess.createDefaultClient(ClusterAccess.java:56)                                                                
        at io.fabric8.maven.plugin.mojo.build.ApplyMojo.executeInternal(ApplyMojo.java:333)                                                                     
        ... 23 more                                                                                                                                             
Caused by: java.net.MalformedURLException: unknown protocol: $USER                                                                                           
        at java.net.URL.<init>(URL.java:600)                                                                                                                    
        at java.net.URL.<init>(URL.java:490)                                                                                                                    
        at java.net.URL.<init>(URL.java:439)                                                                                                                    
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.getProxyUrl(HttpClientUtils.java:186)                                                             
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:127)                                                        
        ... 28 more                                                                                                                                             

It seems, that the maven plugin expects the protocol (http://user:pwd@url:port), but most other Software does not. When I try to add "http://" to the Proxy minishift and other Software are not running correctly.
### Info

* f-m-p version :3.5.31
* Maven version (`mvn -v`) : 3.3.9
* minishift v1.5.0+ae62cf2
```

**Comment by nicolaferraro** [comment]
It seems you're trying to set the proxy in Minishift to access external resources such as images in docker registries, but you don't need to set the proxy to access the local Minishift (or at least, you need to set the `NO_PROXY` flag correctly). Am I correct?

The issue with the proxy configuration is not related to the fabric8 maven plugin, but to the [kubernetes-client](https://github.com/fabric8io/kubernetes-client) used under the hood. Can you report this issue there?

**Comment by hrishin** [comment]
@amoAHCP it may work https://github.com/fabric8io/kubernetes-client/pull/102/files#diff-7a4b549d7e10b88fbe20ebe680f6b25bR62?

Looks like it may be possible to set proxy URL from environment variable `http.proxy` or `https.proxy`.
Could this work @nicolaferraro ?
