### ISSUE TITLE
fabric8:watch is broken

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#1069]
### Description

`fabric8:watch` on f-m-p 3.5.31 is broken:

```
[INFO] --- fabric8-maven-plugin:3.5.31:watch (default-cli) @ random-generator ---
[INFO] F8: Running generator spring-boot
[INFO] F8: spring-boot: Using Docker image fabric8/java-jboss-openjdk8-jdk:1.2 as base / builder
[INFO] F8: Running watcher spring-boot
[INFO] F8: spring-boot: Watching pods with selector LabelSelector(matchExpressions=[], matchLabels={app=random-generator, provider=fabric8, group=meetup}, additionalProperties={}) waiting for a running pod...
[INFO] F8:[NEW] random-generator-1917139499-1dvjc status: Running
[INFO] F8:[NEW] Tailing log of pod: random-generator-1917139499-1dvjc
[INFO] F8:[NEW] Press Ctrl-C to stop tailing the log
[INFO] F8:[NEW]
[INFO] F8:[NEW] random-generator-1917139499-1dvjc status: Running
[INFO] F8: spring-boot: No exposed service found for connecting the dev tools
[INFO] F8: Starting port-forward to pod random-generator-1917139499-1dvjc
[INFO] F8: spring-boot: Running RemoteSpringApplication against endpoint: http://localhost:50130
[INFO] F8: Port forwarding to port 8080 on pod random-generator-1917139499-1dvjc using command /Users/roland/bin/kubectl
[INFO] F8: spring-boot: Spring-Remote:   .   ____          _                                              __ _ _
[INFO] F8: spring-boot: Spring-Remote:  /\\ / ___'_ __ _ _(_)_ __  __ _          ___               _      \ \ \ \
[INFO] F8: spring-boot: Spring-Remote: ( ( )\___ | '_ | '_| | '_ \/ _` |        | _ \___ _ __  ___| |_ ___ \ \ \ \
[INFO] F8: spring-boot: Spring-Remote:  \\/  ___)| |_)| | | | | || (_| []::::::[]   / -_) '  \/ _ \  _/ -_) ) ) ) )
[INFO] F8: spring-boot: Spring-Remote:   '  |____| .__|_| |_|_| |_\__, |        |_|_\___|_|_|_\___/\__\___|/ / / /
[INFO] F8: spring-boot: Spring-Remote:  =========|_|==============|___/===================================/_/_/_/
[INFO] F8: spring-boot: Spring-Remote:  :: Spring Boot Remote ::  (v1.5.7.RELEASE)
[INFO] F8: spring-boot: Spring-Remote:
[INFO] F8: spring-boot: Spring-Remote: 2017-10-12 11:48:09.521  INFO 45389 --- [           main] o.s.b.devtools.RemoteSpringApplication   : Starting RemoteSpringApplication v1.5.7.RELEASE on tichny with PID 45389 (/Users/roland/.m2/repository/org/springframework/boot/spring-boot-devtools/1.5.7.RELEASE/spring-boot-devtools-1.5.7.RELEASE.jar started by roland in /private/tmp/random-generator)
[INFO] F8: spring-boot: Spring-Remote: 2017-10-12 11:48:09.523  INFO 45389 --- [           main] o.s.b.devtools.RemoteSpringApplication   : No active profile set, falling back to default profiles: default
[INFO] F8: spring-boot: Spring-Remote: 2017-10-12 11:48:09.547  INFO 45389 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@a4102b8: startup date [Thu Oct 12 11:48:09 CEST 2017]; root of context hierarchy
[INFO] F8: spring-boot: Spring-Remote: 2017-10-12 11:48:09.887  WARN 45389 --- [           main] o.s.b.d.r.c.RemoteClientConfiguration    : The connection to http://localhost:50130 is insecure. You should use a URL starting with 'https://'.
[INFO] F8: spring-boot: Spring-Remote: 2017-10-12 11:48:09.973  WARN 45389 --- [           main] o.s.b.d.a.OptionalLiveReloadServer       : Unable to start LiveReload server
[INFO] F8: spring-boot: Spring-Remote: 2017-10-12 11:48:10.009  INFO 45389 --- [           main] o.s.b.devtools.RemoteSpringApplication   : Started RemoteSpringApplication in 0.719 seconds (JVM running for 1.043)
[ERROR] F8: spring-boot: Spring-Remote: Exception in thread "File Watcher" java.lang.IllegalStateException: Unexpected 404 response uploading class files
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.util.Assert.state(Assert.java:70)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.remote.client.ClassPathChangeUploader.performUpload(ClassPathChangeUploader.java:116)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.remote.client.ClassPathChangeUploader.onApplicationEvent(ClassPathChangeUploader.java:97)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.remote.client.ClassPathChangeUploader.onApplicationEvent(ClassPathChangeUploader.java:58)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.classpath.ClassPathFileChangeListener.publishEvent(ClassPathFileChangeListener.java:68)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.classpath.ClassPathFileChangeListener.onChange(ClassPathFileChangeListener.java:64)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.filewatch.FileSystemWatcher$Watcher.fireListeners(FileSystemWatcher.java:306)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.filewatch.FileSystemWatcher$Watcher.updateSnapshots(FileSystemWatcher.java:299)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.filewatch.FileSystemWatcher$Watcher.scan(FileSystemWatcher.java:259)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.filewatch.FileSystemWatcher$Watcher.run(FileSystemWatcher.java:239)
[ERROR] F8: spring-boot: Spring-Remote: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by nicolaferraro** [comment]
Mmh, bad.. possible that something changed with sb 1.5.7

**Comment by rhuss** [comment]
Just going to give a demo this evening. What was the last good SB version which worked with fmp watch ?

**Comment by nicolaferraro** [comment]
Tested on 1.4.7.RELEASE

**Comment by rhuss** [comment]
Can confirm that it does not work on 1.5.3. Trying 1.4.7 now ...

**Comment by rhuss** [comment]
Nope, also not with 1.4.7. Trying no a 3.3 fmp, too ....

**Comment by nicolaferraro** [comment]
It worked for me with 1.4.7, have you added spring-boot-starter-web and spring-boot-starter-actuator?
There are some warnings printed to the log during restart, but it worked.

**Comment by rhuss** [comment]
yes, and  also 

```
	<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
		</dependency>
```

**Comment by rhuss** [comment]
this is a test project I, and even fails for fmp 3.3. No idea why.

https://github.com/rhuss/spring-boot-watch-test

**Comment by nicolaferraro** [comment]
Wow.. switched to version `3.5.31` and deleted `application.properties` and it works `mvn clean install fabric8:resource fabric8:build fabric8:watch`.

Don't know why the presence of a empty application.properties changes the behavior..

**Comment by rhuss** [comment]
Hmm. Still does not work for me. Did you update spring-boot, too, to 1.5.6 ?

**Comment by nicolaferraro** [comment]
Was using 1.4.7 in your example app

**Comment by rhuss** [comment]
Just continued a bit on this:

* If I don't add a `spring.devtools.remote.secret` then I get a 403 (thought we generate on the fly)
* Sometimes I get a file upload stream error when saving in the IDE. Looks like a race of compiling vs. upload.
* It depends on the order of Maven goals:

```
mvn clean install fabric8:resource fabric8:build fabric8:watch
```

works, 

```
mvn clean install fabric8:build fabric8:resource fabric8:watch
```

does not (it even does not deploy because of this shitty timestamp label used as default.

**Comment by rhuss** [comment]
I found now a happy path which always worked for me:

* Set name to use latest (`%g/%a:%l`), see also #1093 
* Add a `spring.devtools.remote.secret=3b9c37f9-6777-4c9c-bc76-8f790752f7a6` secret to `application.properties`
* Bind executions:

```xml
				<executions>
					<execution>
						<goals>
							<goal>resource</goal>
							<goal>build</goal>
						</goals>
					</execution>
				</executions>
```

* Call `mvn fabric8:undeploy` when the application is already running
* Call `mvn fabric8:watch`

Only with this *exact* setup it works, if you leave out one it it breakse either with 403 or 404 errors when contactin the devtools internal http server.

I think this should be more robust (e.g. that the executions are not required).

**Comment by pilot911** [comment]
had same problem, solve it via 
```xml
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<configuration>
				<excludeDevtools>false</excludeDevtools>
			</configuration>
		</plugin>
	</plugins>
</build>
```
