### ISSUE TITLE
Exception when using server authentication from settings.xml when building an image

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#108]
```
Caused by: java.lang.NoClassDefFoundError: org/sonatype/plexus/components/sec/dispatcher/SecDispatcher
    at io.fabric8.maven.docker.util.AuthConfigFactory.decrypt(AuthConfigFactory.java:352)
    at io.fabric8.maven.docker.util.AuthConfigFactory.createAuthConfigFromServer(AuthConfigFactory.java:365)
    at io.fabric8.maven.docker.util.AuthConfigFactory.getAuthConfigFromSettings(AuthConfigFactory.java:216)
    at io.fabric8.maven.docker.util.AuthConfigFactory.createAuthConfig(AuthConfigFactory.java:119)
    at io.fabric8.maven.docker.AbstractDockerMojo.prepareAuthConfig(AbstractDockerMojo.java:312)
    at io.fabric8.maven.docker.AbstractDockerMojo.checkImageWithAutoPull(AbstractDockerMojo.java:356)
    at io.fabric8.maven.docker.AbstractBuildSupportMojo.autoPullBaseImage(AbstractBuildSupportMojo.java:107)
    at io.fabric8.maven.docker.AbstractBuildSupportMojo.buildImage(AbstractBuildSupportMojo.java:68)
    at io.fabric8.maven.docker.BuildMojo.buildAndTag(BuildMojo.java:46)
    at io.fabric8.maven.docker.BuildMojo.executeInternal(BuildMojo.java:38)
    at io.fabric8.maven.plugin.docker.BuildMojo.executeInternal(BuildMojo.java:56)
    at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:176)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
```

Its probably a gotcha when embedding d-m-p into f-m-p.

**Comment by rhuss** [comment]
@jimmidyson the latest update should fix this issue. 

Btw the authentication was triggered because you needed to download the base image because you have a sever section "docker.io", "index.docker.io" or "registry.hub.docker.com" in your server settings. 

I will cut a release today.
