### ISSUE TITLE
Exception in reconnect errors while watching builds in fmp

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/fabric8-maven-plugin#1159]
While building various projects using fabric8 maven plugin I often get this Exception in reconnect error messages showing up in logs like this:
```
[INFO] F8: Adding to ImageStream fabric8-maven-sample-spring-boot
[INFO] F8: Starting Build fabric8-maven-sample-spring-boot-s2i
[INFO] F8: Waiting for build fabric8-maven-sample-spring-boot-s2i-12 to complete...
[INFO] F8: ==================================================================
[INFO] F8: Starting S2I Java Build .....
[INFO] F8: S2I binary build from fabric8-maven-plugin detected
[INFO] F8: Copying binaries from /tmp/src/maven to /deployments ...
[INFO] F8: Checking for SpringBoot archive...
[INFO] F8: Found fabric8-maven-sample-spring-boot-3.5-SNAPSHOT.jar...
[INFO] F8: ... done
[INFO] Current reconnect backoff is 1000 milliseconds (T0)
[INFO] F8: 
[INFO] F8: Pushing image 172.30.1.1:5000/myproject/fabric8-maven-sample-spring-boot:latest ...
[INFO] F8: Pushed 0/26 layers, 0% complete
[INFO] F8: Pushed 1/26 layers, 4% complete
[INFO] F8: Pushed 2/26 layers, 8% complete
[INFO] F8: Pushed 3/26 layers, 12% complete
[INFO] F8: Pushed 4/26 layers, 15% complete
[INFO] F8: Pushed 5/26 layers, 19% complete
[INFO] F8: Pushed 6/26 layers, 23% complete
[INFO] F8: Pushed 7/26 layers, 27% complete
[INFO] F8: Pushed 8/26 layers, 31% complete
[INFO] F8: Pushed 9/26 layers, 35% complete
[INFO] F8: Pushed 10/26 layers, 38% complete
[INFO] F8: Pushed 11/26 layers, 42% complete
[INFO] F8: Pushed 12/26 layers, 46% complete
[INFO] F8: Pushed 13/26 layers, 50% complete
[INFO] F8: Pushed 14/26 layers, 54% complete
[INFO] F8: Pushed 15/26 layers, 58% complete
[INFO] F8: Pushed 16/26 layers, 62% complete
[INFO] F8: Pushed 17/26 layers, 65% complete
[INFO] F8: Pushed 18/26 layers, 69% complete
[INFO] F8: Pushed 19/26 layers, 73% complete
[INFO] F8: Pushed 20/26 layers, 77% complete
[INFO] F8: Pushed 21/26 layers, 81% complete
[INFO] F8: Pushed 22/26 layers, 85% complete
[INFO] F8: Pushed 23/26 layers, 89% complete
[INFO] F8: Pushed 24/26 layers, 92% complete
[INFO] F8: Pushed 25/26 layers, 96% complete
[INFO] Current reconnect backoff is 2000 milliseconds (T1)
[INFO] F8: Pushed 26/26 layers, 100% complete
[INFO] F8: Push successful
[INFO] Current reconnect backoff is 4000 milliseconds (T2)
[INFO] F8: Build fabric8-maven-sample-spring-boot-s2i-12 Complete
[INFO] Current reconnect backoff is 8000 milliseconds (T3)
[ERROR] Exception in reconnect
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1b25248 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@f75ac0e[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 6]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:729)
	at io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager$3.run(WatchHTTPManager.java:207)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] F8: Found tag on ImageStream fabric8-maven-sample-spring-boot tag: sha256:54c2c31b15c7de58e304e1ccade8f36a030e811521c70d2cd7175d806ed45af4
[INFO] F8: ImageStream fabric8-maven-sample-spring-boot written to /home/rohan/work/repos/fabric8-maven-plugin/samples/spring-boot/target/fabric8-maven-sample
```
Although these messages don't affect the general build and deploy process of fabric8 maven plugin, but it would be nice if we could get rid of these error messages coming up every time while deploying stuff onto
OpenShift/Kubernetes.

Actually, this exception is thrown by a `ScheduledExecutorService` that is used in Kubernetes client's `watch(..)` method which is being used in fabric8 maven plugin's [OpenShiftBuildService.java](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/core/src/main/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildService.java#L345). During the watch we keep reconnecting after the back off time has passed, without blocking the thread. The exception is thrown at the time when we get some unexpected error without getting any `onFailure()` callback. For more information, See [WatchHttpManager.java](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java#L214)

**Comment by piyush1594** [comment]
This has been fixed in client and will be fixed as we upgrade to client
