### ISSUE TITLE
OpenshiftBuildServiceTest intermittently failing on jenkins.cd.test.fabric8.io

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/fabric8-maven-plugin#1162]
OpenshiftBuildServiceTest is continuously failing on fabric8 Jenkins CI. The problem is that it passes on the local machine but fails on Jenkins with this error:
```
Jan 17, 2018 1:24:28 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[59447] received request: GET /oapi/v1/namespaces/test/imagestreams/myapp HTTP/1.1 and responded: HTTP/1.1 200 OK
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 16.203 sec <<< FAILURE! - in io.fabric8.maven.core.service.openshift.OpenshiftBuildServiceTest
testSuccessfulBuild(io.fabric8.maven.core.service.openshift.OpenshiftBuildServiceTest)  Time elapsed: 10.828 sec  <<< ERROR!
io.fabric8.maven.core.service.Fabric8ServiceException: Unable to build the image using the OpenShift build service
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildServiceTest.testSuccessfulBuild(OpenshiftBuildServiceTest.java:148)
Caused by: org.apache.maven.plugin.MojoExecutionException: Operation: [get]  for kind: [ImageStream]  with name: [myapp]  in namespace: [test]  failed.
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildServiceTest.testSuccessfulBuild(OpenshiftBuildServiceTest.java:148)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [ImageStream]  with name: [myapp]  in namespace: [test]  failed.
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildServiceTest.testSuccessfulBuild(OpenshiftBuildServiceTest.java:148)
Caused by: java.net.SocketTimeoutException: timeout
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildServiceTest.testSuccessfulBuild(OpenshiftBuildServiceTest.java:148)
Caused by: java.net.SocketException: Socket closed
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildServiceTest.testSuccessfulBuild(OpenshiftBuildServiceTest.java:148)
```
The complete build log can be found [here](https://jenkins.cd.test.fabric8.io/job/fabric8io/job/fabric8-maven-plugin/job/master/9/console). This test is blocking the deployment of fabric8 maven plugin to maven central(See #1158 ). In the deployment script, Github tags are being created first and then `mvn deploy` is being run after running tests; where this test creates problems.

**Comment by rohanKanojia** [comment]
I'm approving it as it looks good to me. We just need to fix integration test.

**Comment by rohanKanojia** [comment]
Okay, We are having a mysterious timeout in Jenkins.We're getting intermittent`SocketTimeoutException` 
in this test. Sometimes test fails giving this error and sometimes it just passes without any complaint.

There are two things in my mind:
1. Disable OpenshiftBuildServiceTest(by adding `@Ignore`), but I'm quite skeptical about this since this 
    test is extremely critical from the perspective of fabric8 maven plugin's build process.

2. Fix this test; But the problem is this test is not easily reproducible. I set up a local Jenkins instance
    on which I build it quite a lot but I was unable to reproduce this error. Running this on jenkins.cd. 
    test.fabric8.io reproduced this error once, but running afterward didn't reproduce it.

Looking at logs carefully, i found another `NULLPointerException` i noticed just before the test failure:
```
Jan 25, 2018 11:26:17 AM okhttp3.mockwebserver.MockWebServer$3 execute
SEVERE: MockWebServer[42592] connection from /127.0.0.1 crashed
java.lang.NullPointerException
	at okio.Okio$1.write(Okio.java:78)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
	at okio.RealBufferedSink.writeUtf8(RealBufferedSink.java:53)
	at okhttp3.mockwebserver.MockWebServer.writeHttpResponse(MockWebServer.java:693)
	at okhttp3.mockwebserver.MockWebServer.access$1800(MockWebServer.java:99)
	at okhttp3.mockwebserver.MockWebServer$3.processOneRequest(MockWebServer.java:520)
	at okhttp3.mockwebserver.MockWebServer$3.processConnection(MockWebServer.java:457)
	at okhttp3.mockwebserver.MockWebServer$3.execute(MockWebServer.java:396)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
It's the MockWebServer that we use to mock OpenShift cluster that crashes and henceforth results in
socket closed error. 

I've searched everywhere on the web and after reading some docs regarding connection timeout exception, I found out that preventing `SocketTimeoutException` is beyond our limit. One way to handle it is to define a connection timeout and later handle it in a try-catch block.

**Comment by rohanKanojia** [comment]
Wondering if there is any way to change default timeouts on the underlying HTTP okHttpClient used to interact with the mock server. If we increase it from the default value somehow, it could partially
solve the problem. We can specify web socket timeout in config like:
```
    @Test
    public void testSuccessfulBuild() throws Exception {
        ...

        Config aConfig = new ConfigBuilder()
                .withMasterUrl(mockServer.url("/"))
                .withNamespace("test")
                .withTrustCerts(true)
                .withTlsVersions(TLS_1_0)
                .withWebsocketTimeout(20) // Specifying the timeout in config
                .build();
        OpenShiftClient client = mockServer.createOpenShiftClient(new OpenShiftConfig(aConfig));

        ...
    } 
```
But right now Kubernetes mock server doesn't provide any option for providing customized config for
connections in case of mock server.
