### ISSUE TITLE
Fix SpringbootConfigmapBoosterIT on Openshift 3.7

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/fabric8-maven-plugin#1188]
This booster test is showing weird behavior on Openshift 3.7. Ideally, tests are independent of each other and they use their own resources, but when I run this test on my local Openshift cluster; I get this error on my system:
```
Feb 14, 2018 11:58:27 AM io.fabric8.maven.rt.BaseBoosterIT waitTillApplicationPodStarts
INFO: Waiting to application pod .... 
Feb 14, 2018 11:58:27 AM io.fabric8.maven.rt.BaseBoosterIT waitTillApplicationPodStarts
INFO: waitTillApplicationPodStarts() -> Pod : spring-boot-configmap-greeting-18-xpr7r, isReady : true
Feb 14, 2018 11:58:27 AM io.fabric8.maven.rt.BaseBoosterIT waitTillApplicationPodStarts
INFO: OK ✓ ... Pod wait over.
Feb 14, 2018 12:03:37 PM io.fabric8.maven.rt.BaseBoosterIT makeHttpRequest
INFO: [GET] http://spring-boot-configmap-greeting-myproject.127.0.0.1.nip.io/api/greeting [200 OK]
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,235.662 sec <<< FAILURE! - in io.fabric8.maven.rt.SpringbootConfigmapBoosterIT
deploy_springboot_app_once on deploy_springboot_app_once(io.fabric8.maven.rt.SpringbootConfigmapBoosterIT)(io.fabric8.maven.rt.SpringbootConfigmapBoosterIT)  Time elapsed: 346.242 sec  <<< FAILURE!
java.lang.AssertionError: Actual : Bonjour World from a ConfigMap!, Expected : Hello World from a ConfigMap!
	at io.fabric8.maven.rt.SpringbootConfigmapBoosterIT.assertApplicationEndpoint(SpringbootConfigmapBoosterIT.java:114)
	at io.fabric8.maven.rt.SpringbootConfigmapBoosterIT.assertApplication(SpringbootConfigmapBoosterIT.java:104)
	at io.fabric8.maven.rt.SpringbootConfigmapBoosterIT.deploy_springboot_app_once(SpringbootConfigmapBoosterIT.java:58)


Results :

Failed tests: 
  SpringbootConfigmapBoosterIT.deploy_springboot_app_once:58->assertApplication:104->assertApplicationEndpoint:114 Actual : Bonjour World from a ConfigMap!, Expected : Hello World from a ConfigMap!

Tests run: 2, Failures: 1, Errors: 0, Skipped: 0

```

It is blocking [#1187](https://github.com/fabric8io/fabric8-maven-plugin/issues/1187)

**Comment by piyush1594** [comment]
This has been fixed by #1192
