### ISSUE TITLE
Specify which client is too old when reporting error

### ISSUE THREAD

**Issue by apupier** [fabric8io/fabric8-maven-plugin#1200]
_Please fill out the following information to help us in analyzing the issue, but feel free to skip it if you don't have the information at hand or if it does not apply. Please remove everything which does not apply to the issue. Including this info paragraph ;-)_

### Description

[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.33.fuse-000007:build (build-image) on project karaf-camel-log: Failed to execute the build: Error while trying to build the image: Unable to check image [jboss-fuse-7/fuse-karaf-openshift:1.0] : client version 1.18 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version (Bad Request: 400) -> [Help 1]

### Info

* f-m-p version : 3.5.33
* Maven version (`mvn -v`) :
```
3.3.9
```
* Kubernetes / OpenShift setup and version :
* If it's a bug, how to reproduce :
- launch mvn clean install on https://github.com/fabric8-quickstarts/karaf-camel-log/releases/tag/karaf-camel-log-1.0.0.fuse-000019
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by apupier** [comment]
when launching with debug output, I have:

> [ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.33.fuse-000007:build (build-image) on project camel-ose-karaf-log: Failed to execute the build: Error while trying to build the image: Unable to check image [jboss-fuse-7/fuse-karaf-openshift:1.0] : client version 1.18 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version (Bad Request: 400) -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.33.fuse-000007:build (build-image) on project camel-ose-karaf-log: Failed to execute the build
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
> 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
> 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
> 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
> 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
> 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
> 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to execute the build
> 	at io.fabric8.maven.plugin.mojo.build.BuildMojo.buildAndTag(BuildMojo.java:245)
> 	at io.fabric8.maven.docker.BuildMojo.executeInternal(BuildMojo.java:44)
> 	at io.fabric8.maven.plugin.mojo.build.BuildMojo.executeInternal(BuildMojo.java:222)
> 	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:222)
> 	at io.fabric8.maven.plugin.mojo.build.BuildMojo.execute(BuildMojo.java:193)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
> 	... 20 more
> Caused by: io.fabric8.maven.core.service.Fabric8ServiceException: Error while trying to build the image
> 	at io.fabric8.maven.core.service.kubernetes.DockerBuildService.build(DockerBuildService.java:53)
> 	at io.fabric8.maven.plugin.mojo.build.BuildMojo.buildAndTag(BuildMojo.java:242)
> 	... 26 more
> Caused by: io.fabric8.maven.docker.access.DockerAccessException: Unable to check image [jboss-fuse-7/fuse-karaf-openshift:1.0] : client version 1.18 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version (Bad Request: 400)
> 	at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient.hasImage(DockerAccessWithHcClient.java:303)
> 	at io.fabric8.maven.docker.service.QueryService.hasImage(QueryService.java:173)
> 	at io.fabric8.maven.docker.service.QueryService.pullIfNotPresent(QueryService.java:227)
> 	at io.fabric8.maven.docker.service.QueryService.imageRequiresPull(QueryService.java:217)
> 	at io.fabric8.maven.docker.service.QueryService.imageRequiresAutoPull(QueryService.java:197)
> 	at io.fabric8.maven.docker.service.RegistryService.checkImageWithAutoPull(RegistryService.java:74)
> 	at io.fabric8.maven.docker.service.BuildService.autoPullBaseImage(BuildService.java:211)
> 	at io.fabric8.maven.docker.service.BuildService.buildImage(BuildService.java:58)
> 	at io.fabric8.maven.core.service.kubernetes.DockerBuildService.build(DockerBuildService.java:48)
> 	... 27 more
> Caused by: io.fabric8.maven.docker.access.hc.http.HttpRequestException: client version 1.18 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version (Bad Request: 400)
> 	at io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegate$StatusCodeCheckerResponseHandler.handleResponse(ApacheHttpClientDelegate.java:177)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
> 	at io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegate.get(ApacheHttpClientDelegate.java:74)
> 	at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient.hasImage(DockerAccessWithHcClient.java:301)
> 	... 35 more

**Comment by oscerd** [comment]
It's your docker-client.

**Comment by apupier** [comment]
> It's your docker-client.

this is what it seems yes. it owuld be nice to improve the error message to mention it. and tomention from where it is taking the client because everything seems up to date:

```
C:\Users\Aurelien Pupier>docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.24)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:15:52 2017
  OS/Arch:      windows/amd64
  Experimental: true
```

![image](https://user-images.githubusercontent.com/1105127/36312212-edee687c-132d-11e8-805d-e33e55c0b1da.png)

**Comment by apupier** [comment]
found some other interesting logs. A first time it retrieves the correct docker client version 1.35 and after it complains about bad version

```
[DEBUG] F8: RESPONSE HTTP/1.1 200 OK
Api-Version: 1.35
Content-Length: 638
Content-Type: application/json
Date: Fri, 16 Feb 2018 12:52:38 GMT
Docker-Experimental: true
Ostype: windows
Server: Docker/17.12.0-ce (windows)
```


```
[DEBUG] F8: RESPONSE HTTP/1.1 400 Bad Request
Api-Version: 1.35
Content-Length: 117
Content-Type: text/plain; charset=utf-8
Date: Fri, 16 Feb 2018 12:52:59 GMT
Ostype: windows
Server: Docker/17.12.0-ce (windows)
X-Content-Type-Options: nosniff
```

**Comment by apupier** [comment]
io.fabric8.maven.docker.service.DockerAccessFactory.API_VERSION is mentioning the "1.18" version by default.
Maybe several call to https://github.com/fabric8io/docker-maven-plugin/blob/8ade1e2cbfa2d76a30fdf73f6fc34400ecca6e07/src/main/java/io/fabric8/maven/docker/service/DockerAccessFactory.java#L38 would result to not find a version one time and then use this default one?

**Comment by rohanKanojia** [comment]
@apupier : Could you please file an issue on dmp also?

**Comment by rhuss** [comment]
Indeed, d-m-p requires at least 1.18. However, if you use certain features which have been introduced later, the minimal version is increased (e.g. to 1.24 when using HEALTHCHECK). 

You can overwrite this minimal version by using the property `docker.apiVersion` or set the configuration parameter `apiVersion` in the XML configuration (top-level).

However, I wonder whether we really have to send any API version to the Docker daemon if we don't require any special handling.

I opened https://github.com/fabric8io/docker-maven-plugin/issues/1060 do deal with this on the d-m-p. After this is fixed over there in d-m-p land we need to upgrade the internal d-m-p (#758)

**Comment by rohanKanojia** [comment]
@rhuss : Do we require this issue to be open as we already have one issue filed for upgrading dmp?
