### ISSUE TITLE
Redeploy of project fails if using PVC and already present on cluster

### ISSUE THREAD

**Issue by cchet** [fabric8io/fabric8-maven-plugin#1219]
### Description
When my service uses a PVC, which has already been created in openshift, then the redeploy fails because its tried to update the PVC. I use the Technical Preview of Redhat Integration Service 2.0.
I'm not sure if there is a setting I'm missing, or if this is a bug.

### Info
* **IDE:**  IntelliJ 2017.3.4 Ultimate
* **Maven:** Intellij Bundled Maven 3
* **Fabric8:**  fabric8-project-bom-camel-spring-boot:2.2.170.redhat-000022, fabric8-maven-plugin:3.1.80.redhat-000022
* **OpenShift Master:** v3.6.0+c4dd4cf
* **Kubernetes Master:** v1.6.1+5115d708d7 
* **Sample Project:** git@github.com:cchet-thesis-msc/integration-service-conax.git
**  Use settings.xml located in /configuration folder
** clean install fabric8:deploy // fails if service already deployed to cluster

### Error Log
> [INFO] F8: Using OpenShift at https://10.0.75.2:8443/ in namespace fis with manifest D:\repositories\Github\cchet-thesis-msc\integration-service-conax\target\classes\META-INF\fabric8\openshift.yml 
[INFO] OpenShift platform detected
[INFO] Using project: fis
[INFO] Updating a Service from openshift.yml
[INFO] Updated Service: \target\fabric8\applyJson\fis\service-integration-conax.json
[INFO] Updating PersistentVolumeClaim from openshift.yml
[ERROR] Failed to update PersistentVolumeClaim from openshift.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://10.0.75.2:8443/api/v1/namespaces/fis/persistentvolumeclaims/data. Message: PersistentVolumeClaim "data" is invalid: spec: Forbidden: field is immutable after creation. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec, message=Forbidden: field is immutable after creation, reason=FieldValueForbidden, additionalProperties={})], group=null, kind=PersistentVolumeClaim, name=data, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=PersistentVolumeClaim "data" is invalid: spec: Forbidden: field is immutable after creation, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).. PersistentVolumeClaim(apiVersion=v1, kind=PersistentVolumeClaim, metadata=ObjectMeta(annotations=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={provider=fabric8, project=integration-conax, version=1.0-SNAPSHOT, group=com.gepardec.sypoc}, name=data, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PersistentVolumeClaimSpec(accessModes=[ReadWriteOnce], resources=ResourceRequirements(limits=null, requests={storage=Quantity(amount=100Mi, format=null, additionalProperties={})}, additionalProperties={}), selector=null, volumeName=null, additionalProperties={}), status=null, additionalProperties={})
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://10.0.75.2:8443/api/v1/namespaces/fis/persistentvolumeclaims/data. Message: PersistentVolumeClaim "data" is invalid: spec: Forbidden: field is immutable after creation. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec, message=Forbidden: field is immutable after creation, reason=FieldValueForbidden, additionalProperties={})], group=null, kind=PersistentVolumeClaim, name=data, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=PersistentVolumeClaim "data" is invalid: spec: Forbidden: field is immutable after creation, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:314)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:267)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:236)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:229)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleReplace(OperationSupport.java:213)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleReplace(BaseOperation.java:585)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$2.apply(HasMetadataOperation.java:87)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$2.apply(HasMetadataOperation.java:82)
	at io.fabric8.kubernetes.api.model.DoneablePersistentVolumeClaim.done(DoneablePersistentVolumeClaim.java:26)
	at io.fabric8.kubernetes.api.model.DoneablePersistentVolumeClaim.done(DoneablePersistentVolumeClaim.java:5)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:94)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:32)
	at io.fabric8.kubernetes.api.Controller.applyResource(Controller.java:879)
	at io.fabric8.kubernetes.api.Controller.applyEntity(Controller.java:282)
	at io.fabric8.kubernetes.api.Controller.apply(Controller.java:225)
	at io.fabric8.maven.plugin.mojo.build.ApplyMojo.applyEntities(ApplyMojo.java:461)
	at io.fabric8.maven.plugin.mojo.develop.RunMojo.applyEntities(RunMojo.java:55)
	at io.fabric8.maven.plugin.mojo.build.ApplyMojo.executeInternal(ApplyMojo.java:413)
	at io.fabric8.maven.plugin.mojo.AbstractFabric8Mojo.execute(AbstractFabric8Mojo.java:77)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by cchet** [comment]
Can anyone help me with this issue ?

**Comment by cchet** [comment]
I had an invalid deployment.yml file, but redhat release '**3.1.80.redhat-000022**' did not warn me about that, but release '**3.5.38**' did.

I had
> 
          volumeMounts:
            - mountPath: /data
              name: data
          volumeMounts:
            - mountPath: /config
              name: config

instead of

> 
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /config
              name: config

So was a copy paste issue :)
