### ISSUE TITLE
Unable to build empty project due to artifact-is.yml file not found

### ISSUE THREAD

**Issue by nicolaferraro** [fabric8io/fabric8-maven-plugin#1247]
### Description
Tracking https://issues.jboss.org/browse/OSFUSE-709.

When trying to install a empty project, the plugin fails with a misleading message.

```
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to install artifact org.jboss.qe:java-helloworld:yml:is:1.0-SNAPSHOT: /home/nferraro/git/stuff/java-helloworld/target/java-helloworld-is.yml (No such file or directory)
        at org.apache.maven.plugin.install.InstallMojo.execute(InstallMojo.java:153)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 24 more
Caused by: org.apache.maven.artifact.installer.ArtifactInstallationException: Failed to install artifact org.jboss.qe:java-helloworld:yml:is:1.0-SNAPSHOT: /home/nferraro/git/stuff/java-helloworld/target/java-helloworld-is.yml (No such file or directory)
        at org.apache.maven.artifact.installer.DefaultArtifactInstaller.install(DefaultArtifactInstaller.java:111)
        at org.apache.maven.plugin.install.InstallMojo.execute(InstallMojo.java:145)
        ... 26 more
Caused by: org.eclipse.aether.installation.InstallationException: Failed to install artifact org.jboss.qe:java-helloworld:yml:is:1.0-SNAPSHOT: /home/nferraro/git/stuff/java-helloworld/target/java-helloworld-is.yml (No such file or directory)
        at org.eclipse.aether.internal.impl.DefaultInstaller.install(DefaultInstaller.java:280)
        at org.eclipse.aether.internal.impl.DefaultInstaller.install(DefaultInstaller.java:195)
        at org.eclipse.aether.internal.impl.DefaultInstaller.install(DefaultInstaller.java:152)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.install(DefaultRepositorySystem.java:377)
        at org.apache.maven.artifact.installer.DefaultArtifactInstaller.install(DefaultArtifactInstaller.java:107)
        ... 27 more
Caused by: java.io.FileNotFoundException: /home/nferraro/git/stuff/java-helloworld/target/java-helloworld-is.yml (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.eclipse.aether.internal.impl.DefaultFileProcessor.copy(DefaultFileProcessor.java:162)
        at org.eclipse.aether.internal.impl.DefaultFileProcessor.copy(DefaultFileProcessor.java:150)
        at org.eclipse.aether.internal.impl.DefaultInstaller.install(DefaultInstaller.java:267)
        ... 31 more
```

### Info

* f-m-p version : 3.5.38
* Maven version (`mvn -v`) :
```
Apache Maven 3.5.0 (Red Hat 3.5.0-6)
Maven home: /usr/share/maven
Java version: 1.8.0_161, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-5.b14.fc27.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.7-300.fc27.x86_64", arch: "amd64", family: "unix"
```
* Kubernetes / OpenShift setup and version : 3.7.1
* If it's a bug, how to reproduce : `mvn clean fabric8:resource fabric8:build fabric8:deploy` on a empty project with f-m-p declared as:

```
<build>
	<plugins>
		<plugin>
			<groupId>io.fabric8</groupId>
			<artifactId>fabric8-maven-plugin</artifactId>
			<version>3.5.38</version>
		</plugin>
	</plugins>
</build>
```

**Comment by piyush1594** [comment]
As the PR is merged, I am closing this.
