### ISSUE TITLE
Proxy options in fabric8 maven plugin

### ISSUE THREAD

**Issue by vrlgohel** [fabric8io/fabric8-maven-plugin#1359]
### Description
Proxy options in fabric8 maven plugin
### Info
openshift environment sits behind a corporate proxy and on deploying with 'mvn fabric8:deploy', we can see there are 502 error code, 

```
[WARNING] F8: Cannot access cluster for detecting mode: Unexpected response code for CONNECT: 502
[INFO] F8: Running in Kubernetes mode
[INFO] F8: Running generator spring-boot
[INFO] F8: spring-boot: Using ImageStreamTag 'fis-java-openshift:2.0' from namespace 'xxx-xxx' as builder image
[INFO] F8: using resource templates from C\examples\examples-ocp-archetype\fuse70-spring-boot\src\main\fabric8
[INFO] F8: fmp-service: Adding a default service 'fuse70-spring-boot' with ports [8080]
[INFO] F8: spring-boot-health-check: Adding readiness probe on port 8081, path='/health', scheme='HTTP', with initial delay 10 seconds
[INFO] F8: spring-boot-health-check: Adding liveness probe on port 8081, path='/health', scheme='HTTP', with initial delay 180 seconds
[INFO] F8: fmp-revision-history: Adding revision history limit to 2
[INFO] F8: f8-icon: Adding icon for deployment
[INFO] F8: f8-icon: Adding icon for service
[INFO] F8: validating fuse70-spring-boot\target\classes\META-INF\fabric8\openshift\fuse70-spring-boot-deploymentconfig.yml resource
[ERROR] Failed to load json schema!
java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
```
* f-m-p version :
* Maven version (`mvn -v`) : 3.5.2
* Kubernetes / OpenShift setup and version : ose v3.9.0 and kubernetes v1.9.1

Maven proxy settings to by-pass the proxy does not help much. 
`mvn clean -DskipTests fabric8:deploy -Popenshift -Dfabric8.generator.fromMode=istag -Dfabric8.generator.from=namespace/fis-java-openshift:2.0 -Dhttp.proxy Host=xxxxx -Dhttp.proxyPort=xxxx -Dhttp.nonProxyHosts=hostname -Dfabric8.mode=openshift `

The only option we see when openshift master is behind a proxy is to manually deploy importing YAML or JSON file, generated using the fabric:resource, but on production/development environments, manually deploying does not seem to be an elegant approach. 

We need a way in the plugin to have some options to filter and by-pass the proxy if openshift cluster is setting behind.

**Comment by rohanKanojia** [comment]
@rhuss : Does it make sense to provide these kinds of options to by-pass proxy in the plugin itself? WDYT?

**Comment by vrlgohel** [comment]
@rhuss, practically speaking, Maven respects the usual Java properties http.proxyHost and others. So, if the plugin is Maven based, it would be nice to have a way to respect the properties in the plugin as well.

**Comment by rhuss** [comment]
I agree that we should honour proxy options, too, if the plugin has to reach out.

But for this particular issue at end I would much more favour a solution where the schema to validate is *not* downloaded everytime. I wonder whether it wouldn't be possible to include the Json schema directly within the plugin (maybe for all API versions known) and reach out to the net only for unknown APIs (e.g. those which are introduced after the plugin was released).

This would help in speeding up fmp and also help for offline mode to not unnecessarily breaking the build.

**Comment by nicolaferraro** [comment]
The fix to use a embedded version of the schema has been added a while ago by @hrishin and should be present in latest version.
@vrlgohel, are you using a old version?

**Comment by vrlgohel** [comment]
@nicolaferraro, i am using fabric8-maven-parent version, 3.5.33.

**Comment by rohanKanojia** [comment]
@vrlgohel : Could you please try with latest version i.e. `3.5.41`?

**Comment by vrlgohel** [comment]
@rohanKanojia , testing with the latest version 3.5.41, there is a different WARN message now, 


```
[INFO] --- fabric8-maven-plugin:3.5.41:build (default) @ fuse70-spring-boot ---
--
[INFO] F8: Using OpenShift build with strategy S2I
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.675 s
[INFO] Finished at: 2018-08-28T09:43:37+01:00
[INFO] Final Memory: 71M/912M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.41:build (default) on project fuse70-spring-boot: Execution default of goal io.fabric8:fabric8-maven-plugin:3.5.41:build failed: Failed to parse ipAddresskubernetes.default.svc: Unknown host kubernetes.default.svc -> [Help 1]

```

**Comment by JackMj** [comment]
Has there been any updates to this issue since closed?

**Comment by rohanKanojia** [comment]
@JackMj : Are you facing this error too? On which version?
