### ISSUE TITLE
fabric8:watch fails

### ISSUE THREAD

**Issue by ccshih** [fabric8io/fabric8-maven-plugin#1522]
### Description

I tried to run `fabric8:watch` but got this error:

`[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.40:watch (default-cli) on project test: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:3.5.40:watch failed: No <dockerHost> given, no DOCKER_HOST environment variable, no read/writable '/var/run/docker.sock' or '//./pipe/docker_engine' and no external provider like Docker machine configured -> [Help 1]`

I ran on OpenShift mode and built docker images on OpenShift nodes. This works for `fabric8:build`, so I think another local Docker engine is unnecessary for `fabric8:watch`.

	<properties>
		<fabric8.mode>openshift</fabric8.mode>
		<fabric8.skipResourceValidation>true</fabric8.skipResourceValidation>
		<fabric8.debug.enabled>true</fabric8.debug.enabled>
		<fabric8.namespace>test</fabric8.namespace>
	</properties>

### Info
* f-m-p version : 3.5.40
* Maven version (`mvn -v`) : 3.3.9
* Kubernetes / OpenShift setup and version : OpenShift 3.9

**Comment by rohanKanojia** [comment]
@ccshih : Could you please try on latest version `4.0.0-M2`?? It got fixed recently

**Comment by rohanKanojia** [comment]
@ccshih : looking at your logs it looks like you're not connected to your docker deamon. What does a normal command like `docker ps` return in your case? If you're doing all this on minishift please do : `eval $(minishift docker-env)`  and check goals again?

**Comment by ccshih** [comment]
@rohanKanojia:  I run in OpenShift mode and build images in an three-node OpenShift cluster. I don't require a local docker daemon to run `fabric8:build`, so neither does  `fabric8:watch`? Will try `4.0.0-M2` later. Thanks for your help.

**Comment by rohanKanojia** [comment]
@ccshih : I tried reproducing it myself but looks like it's broken on `4.0.0-M2` but it is working on `4.0.0-M1`

**Comment by mojsha** [comment]
I am facing the same issue. Would appreciate if this issue was fixed and no requirement was needed on Docker as most of us are working towards an OpenShift cluster.

**Comment by rohanKanojia** [comment]
@mojsha @ccshih : Could you please try again on latest release 4.0.0?

**Comment by ccshih** [comment]
Got an `NullPointerException` in deploy phase, maybe I should reconfigure for 4.0.0?
```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:4.0.0:deploy (deploy) on project ******: Execution deploy of goal io.fabric8:fabric8-maven-plugin:4.0.0:deploy failed. NullPointerException -> [Help 1]
```

**Comment by rohanKanojia** [comment]
@ccshih Please see http://maven.fabric8.io/#fabric8:watch on what to configure for spring boot watch to work. Could you please share verbose logs (`mvn fabric8:deploy -X`)? I've created a video on YouTube for flow of https://www.youtube.com/watch?v=UtdtSX8g36E&t=5s.

**Comment by hetzge** [comment]
The **NullPointerException** sounds like: https://github.com/fabric8io/fabric8-maven-plugin/issues/1515
You also have the 'fabric8.namespace' in your properties.

**Comment by rohanKanojia** [comment]
@hetzge @ccshih : This seems to be a pretty serious issue. Could you please share your logs with `-X` option? Could anyone please share a pom which reproduces this issue?

**Comment by ccshih** [comment]
```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:4.0.0:deploy (default-cli) on project logevent-stream-consumer: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:4.0.0:deploy failed. NullPointerException -> [Help
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:4.0.0:deploy (default-cli) on project logevent-stream-consumer: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:4.0
failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:4.0.0:deploy failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.NullPointerException
        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
        at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:75)
        at java.base/java.lang.reflect.Field.set(Field.java:780)
        at io.fabric8.maven.core.access.ClusterConfiguration$Builder.from(ClusterConfiguration.java:149)
        at io.fabric8.maven.plugin.mojo.AbstractFabric8Mojo.getClusterConfiguration(AbstractFabric8Mojo.java:90)
        at io.fabric8.maven.plugin.mojo.build.ApplyMojo.executeInternal(ApplyMojo.java:207)
        at io.fabric8.maven.plugin.mojo.develop.DeployMojo.executeInternal(DeployMojo.java:47)
        at io.fabric8.maven.plugin.mojo.AbstractFabric8Mojo.execute(AbstractFabric8Mojo.java:65)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
```


```

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>test</groupId>
	<artifactId>logevent-stream-consumer</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>logevent-stream-consumer</name>
	<description>Consume log events using kafka stream</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.2.RELEASE</version>
		<relativePath />
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<fabric8.mode>openshift</fabric8.mode>
		<fabric8.skipResourceValidation>true</fabric8.skipResourceValidation>
		<fabric8.debug.enabled>true</fabric8.debug.enabled>
		<fabric8.debug.port>7474</fabric8.debug.port>
		<fabric8.namespace>test</fabric8.namespace>
	</properties>

	<dependencies>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-stream-kafka</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-kafka-streams</artifactId>
		</dependency>

		<dependency>
			<groupId>org.rocksdb</groupId>
			<artifactId>rocksdbjni</artifactId>
			<version>5.0.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-test-support</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
		</dependency>

	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-stream-dependencies</artifactId>
				<version>Elmhurst.RELEASE</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<compilerArgument>-parameters</compilerArgument>
				</configuration>
			</plugin>
			<plugin>
				<groupId>io.fabric8</groupId>
				<artifactId>fabric8-maven-plugin</artifactId>
				<version>4.0.0</version>
			</plugin>
		</plugins>
	</build>

</project>

```
