### ISSUE TITLE
Test behavior of Fabric8 Watch on Windows

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/fabric8-maven-plugin#1800]
I had discussions with @mojsha and seems like `fabric8:watch` still seems to be broken on windows platform. Although I haven't tried it myself out on windows, but I think we need to check and fix it accordingly.
This [video](https://www.youtube.com/watch?v=QI7O4oDlUJg&t=6s) gives a walkthrough with `fabric8:watch`, we just need to test it on windows and check.

**Comment by mojsha** [comment]
@rohanKanojia Just to clarify that the same issue appears on Linux. The exception occurs when it detects a change and wants to run a Live Update, and this is how it looks:

```
[ERROR] F8: spring-boot: Spring-Remote: Exception in thread "File Watcher" java.lang.IllegalStateException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching localhost found.
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.remote.client.ClassPathChangeUploader.onApplicationEvent(ClassPathChangeUploader.java:100)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.remote.client.ClassPathChangeUploader.onApplicationEvent(ClassPathChangeUploader.java:58)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.classpath.ClassPathFileChangeListener.publishEvent(ClassPathFileChangeListener.java:68)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.classpath.ClassPathFileChangeListener.onChange(ClassPathFileChangeListener.java:64)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.filewatch.FileSystemWatcher$Watcher.fireListeners(FileSystemWatcher.java:307)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.filewatch.FileSystemWatcher$Watcher.updateSnapshots(FileSystemWatcher.java:300)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.filewatch.FileSystemWatcher$Watcher.scan(FileSystemWatcher.java:260)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.filewatch.FileSystemWatcher$Watcher.run(FileSystemWatcher.java:240)
[ERROR] F8: spring-boot: Spring-Remote: 	at java.lang.Thread.run(Thread.java:748)
[ERROR] F8: spring-boot: Spring-Remote: Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching localhost found.
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:78)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:112)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.remote.client.HttpHeaderInterceptor.intercept(HttpHeaderInterceptor.java:57)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:88)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:72)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.remote.client.ClassPathChangeUploader.performUpload(ClassPathChangeUploader.java:115)
[ERROR] F8: spring-boot: Spring-Remote: 	at org.springframework.boot.devtools.remote.client.ClassPathChangeUploader.onApplicationEvent(ClassPathChangeUploader.java:97)
[ERROR] F8: spring-boot: Spring-Remote: 	... 13 more
[ERROR] F8: spring-boot: Spring-Remote: Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching localhost found.
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:214)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.util.HostnameChecker.match(HostnameChecker.java:96)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:200)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
[ERROR] F8: spring-boot: Spring-Remote: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
[ERROR] F8: spring-boot: Spring-Remote: 	... 34 more
```

**Comment by rohanKanojia** [comment]
@manusa : Would it be possible for you to try Fabric8 Watch out on Windows/Ubuntu?
