### ISSUE TITLE
mac m1 install fabric8-maven-plugin error

### ISSUE THREAD

**Issue by weihubeats** [fabric8io/fabric8-maven-plugin#1840]
### Description
```java
java.lang.UnsatisfiedLinkError: /private/var/folders/_g/vj4459vs18l8gx_d8qks25240000gn/T/jffi8711101352606354001.dylib: dlopen(/private/var/folders/_g/vj4459vs18l8gx_d8qks25240000gn/T/jffi8711101352606354001.dylib, 0x0001): tried: '/private/var/folders/_g/vj4459vs18l8gx_d8qks25240000gn/T/jffi8711101352606354001.dylib' (fat file, but missing compatible architecture (have (i386,x86_64), need (arm64e)))
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.kenai.jffi.internal.StubLoader.loadFromJar(StubLoader.java:376)
	at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:258)
	at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:449)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.kenai.jffi.Init.load(Init.java:68)
	at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:49)
	at com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:45)
	at com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
	at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
	at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
	at com.kenai.jffi.Type.resolveSize(Type.java:155)
	at com.kenai.jffi.Type.size(Type.java:138)
	at jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:178)
	at jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
	at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:57)
	at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:41)
	at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:53)
	at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:49)
	at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
	at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
	at jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
	at jnr.ffi.LibraryLoader.create(LibraryLoader.java:73)
	at jnr.unixsocket.Native.<clinit>(Native.java:76)
	at jnr.unixsocket.UnixSocketChannel.<init>(UnixSocketChannel.java:101)
	at jnr.unixsocket.UnixSocketChannel.open(UnixSocketChannel.java:60)
	at io.fabric8.maven.docker.access.util.LocalSocketUtil.canConnectUnixSocket(LocalSocketUtil.java:38)
	at io.fabric8.maven.docker.access.DockerConnectionDetector$UnixSocketDockerHostProvider.getConnectionParameter(DockerConnectionDetector.java:109)
	at io.fabric8.maven.docker.access.DockerConnectionDetector.detectConnectionParameter(DockerConnectionDetector.java:78)
	at io.fabric8.maven.docker.service.DockerAccessFactory.createDockerAccess(DockerAccessFactory.java:34)
	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:227)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.execute(BuildMojo.java:225)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```

I tried to install socat and set up redirection and still got the same error

### Info
version:
- fabric8-maven-plugin:4.4.2
- spring-boot:2.7.0
- mac: 12.5.1 Apple M1
- docker:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/42484192/202151329-8bc8aa2c-9608-4b39-a693-d21ced2394d3.png">
- minikube: v1.28.0

**Comment by manusa** [comment]
It seems the plugin has trouble accessing your docker host.

Anyway, this plugin is no longer maintained. Please consider moving to JKube: https://github.com/eclipse/jkube

**Comment by rohanKanojia** [comment]
@weihubeats : Hi, Fabric8 Maven Plugin has been rebranded to [Kubernetes Maven Plugin](https://search.maven.org/artifact/org.eclipse.jkube/kubernetes-maven-plugin/1.10.0/maven-plugin).

Please try migrating to JKube, you can do this via this command:
```
mvn org.eclipse.jkube:kubernetes-maven-plugin:migrate
```

**Comment by manusa** [comment]
There were some issues with Apple M1 that were fixed in JKube:
- https://github.com/eclipse/jkube/issues/1470
- https://github.com/eclipse/jkube/pull/1471

Which look very similar to your problem.

**Comment by weihubeats** [comment]
> @weihubeats : Hi, Fabric8 Maven Plugin has been rebranded to [Kubernetes Maven Plugin](https://search.maven.org/artifact/org.eclipse.jkube/kubernetes-maven-plugin/1.10.0/maven-plugin).
> 
> @ weihuats: 嗨，Fabric8 Maven 插件已经重新命名为 Kubernetes Maven 插件。
> 
> Please try migrating to JKube, you can do this via this command:
> 
> 请尝试迁移到 JKube，您可以通过以下命令完成:
> 
> ```
> mvn org.eclipse.jkube:kubernetes-maven-plugin:migrate
> ```

Ok thank you very much

**Comment by weihubeats** [comment]
When I use kubernetes-maven-plugin he gets the following error, what configuration am I missing?
```java
'boolean org.fusesource.jansi.AnsiConsole.isInstalled()'
```

**Comment by rohanKanojia** [comment]
@weihubeats : Were you able to resolve your issue?

**Comment by weihubeats** [comment]
Of course,@manusa  helped me out, ref https://github.com/eclipse/jkube/issues/1915
