### ISSUE TITLE
Allow to turn of enrichers from ENV/JVM system property

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-maven-plugin#231]
When building fabric8-forge it takes 30 minutes and part of the slowness is that each quickstart that fabric8-forge can build is built and tested. 

That build takes some time. 

I wonder if its possible to turn off GitEnricher / enricher's in general?

Then we could have a mvn profile that sets a ENV or JVM system property to turn it off, so the build can be faster.

```
[info] F8> Looking at repo with directory /mnt/hudson_workspace/workspace/fabric8-forge-pullreq-merge/.git
[WARNING] Could not lookup service:gogs in namespace:default, due to: An error has occurred.
[INFO] Connecting to service gogs on : from $GOGS_SERVICE_HOST and $GOGS_SERVICE_PORT
[warn] F8> Failed: java.lang.IllegalArgumentException: No kubernetes service could be found for name: gogs in namespace: default
java.lang.IllegalArgumentException: No kubernetes service could be found for name: gogs in namespace: default
    at io.fabric8.kubernetes.api.KubernetesHelper.getServiceURL(KubernetesHelper.java:1297)
    at io.fabric8.kubernetes.api.KubernetesHelper.getServiceURL(KubernetesHelper.java:1259)
    at io.fabric8.maven.enricher.git.GitEnricher.getAnnotations(GitEnricher.java:129)
    at io.fabric8.maven.plugin.enricher.EnricherManager$Extractor$2.extract(EnricherManager.java:154)
    at io.fabric8.maven.plugin.enricher.EnricherManager.extract(EnricherManager.java:130)
    at io.fabric8.maven.plugin.enricher.EnricherManager.extractAnnotations(EnricherManager.java:120)
    at io.fabric8.maven.plugin.enricher.MetadataEnricherVisitor.visit(MetadataEnricherVisitor.java:46)
    at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:70)
    at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:10)
    at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:67)
    at io.fabric8.maven.plugin.enricher.EnricherManager.visit(EnricherManager.java:174)
    at io.fabric8.maven.plugin.enricher.EnricherManager.enrichLabels(EnricherManager.java:71)
    at io.fabric8.maven.plugin.ResourceMojo.generateKubernetesResources(ResourceMojo.java:366)
    at io.fabric8.maven.plugin.ResourceMojo.execute(ResourceMojo.java:160)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[warn] F8> No kubernetes service could be found for name: gogs in namespace: default
[WARNING] Could not lookup service:jenkins in namespace:default, due to: An error has occurred.
[INFO] Connecting to service jenkins on : from $JENKINS_SERVICE_HOST and $JENKINS_SERVICE_PORT
[warn] F8> No kubernetes service could be found for name: jenkins in namespace: default
```

**Comment by rhuss** [comment]
This should be already possible: You can defined a Maven profiles with an exclude / include configuration for generators and enrichers (described in https://maven.fabric8.io/#generators for generators, but its the same for enricher).

In addition, but yet undocumented there are f-m-p "profiles" like [this one](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/samples/external-resources/src/main/fabric8/profiles.yaml). This allows to defined a fixed set of enricher and generator configuration (can be in stored in a dependency on the classpath, too)  and then can be refered with a single Maven property `fabric8.profile`.  I hope that I can document it as soon as possible (hopefully still before my PTO), but I can help in integrating that right now. just ping me.

**Comment by davsclaus** [comment]
Thanks Roland, would the configuration be something like

```
      <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>fabric8-maven-plugin</artifactId>
        <version>${fabric8.maven.plugin.version}</version>
        <configuration>
          <customizer>
            <java.app.mainClass>org.apache.camel.cdi.Main</java.app.mainClass>
          </customizer>
          <enricher>
            <excludes>
              <exclude>f8-git</exclude>
            </excludes>
          </enricher>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>resource</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

That seems to still contact git
```
[info] F8> Adding a default Service with ports [8778]
[info] F8> Adding a default Deployment
[info] F8> Looking at repo with directory /Users/davsclaus/workspace/fabric8-forge/.git
[WARNING] Could not lookup service:gogs in namespace:default, due to: An error has occurred.
[INFO] Connecting to service gogs on : from $GOGS_SERVICE_HOST and $GOGS_SERVICE_PORT
[warn] F8> Failed: java.lang.IllegalArgumentException: No kubernetes service could be found for name: gogs in namespace: default
java.lang.IllegalArgumentException: No kubernetes service could be found for name: gogs in namespace: default
       	at io.fabric8.kubernetes.api.KubernetesHelper.getServiceURL(KubernetesHelper.java:1297)
       	at io.fabric8.kubernetes.api.KubernetesHelper.getServiceURL(KubernetesHelper.java:1259)
       	at io.fabric8.maven.enricher.git.GitEnricher.getAnnotations(GitEnricher.java:129)
       	at io.fabric8.maven.plugin.enricher.EnricherManager$Extractor$2.extract(EnricherManager.java:154)
       	at io.fabric8.maven.plugin.enricher.EnricherManager.extract(EnricherManager.java:130)
       	at io.fabric8.maven.plugin.enricher.EnricherManager.extractAnnotations(EnricherManager.java:120)
       	at io.fabric8.maven.plugin.enricher.MetadataEnricherVisitor.visit(MetadataEnricherVisitor.java:46)
       	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:70)
       	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:10)
       	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:67)
       	at io.fabric8.maven.plugin.enricher.EnricherManager.visit(EnricherManager.java:174)
       	at io.fabric8.maven.plugin.enricher.EnricherManager.enrichLabels(EnricherManager.java:71)
       	at io.fabric8.maven.plugin.ResourceMojo.generateKubernetesResources(ResourceMojo.java:366)
       	at io.fabric8.maven.plugin.ResourceMojo.execute(ResourceMojo.java:160)
       	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
       	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
       	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
       	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
       	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
       	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
       	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
       	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
       	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
       	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
       	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
       	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
       	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:483)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[warn] F8> No kubernetes service could be found for name: gogs in namespace: default
[warn] F8> Cannot find $BUILD_ID so must not be inside a Jenkins build
[info] F8> Looking at repo with directory /Users/davsclaus/workspace/fabric8-forge/.git
```

**Comment by rhuss** [comment]
@davsclaus configuration looks good, but the enricher to exclude here is `f8-cd` .

**Comment by davsclaus** [comment]
Thanks it would however still be lovely if you can exclude from ENV as we have a bunch of tests that create from archetypes, and then run a maven invoker to run the package goal. So if I need to exclude the git, then I need to thinker with the generated pom.xml from the generated source code from the archetype, before running the maven invoker.

I think for people who are not using fabric8 cd-pipeline with git etc would get annoyed that git enricher is there.

Also when I build fabric8-forge I see this git attempt made in row which slows down
```
[INFO] Looking at repo with directory /Users/davsclaus/workspace/fabric8-forge/.git
[INFO] Looking at repo with directory /Users/davsclaus/workspace/fabric8-forge/.git
[INFO] Looking at repo with directory /Users/davsclaus/workspace/fabric8-forge/.git
[INFO] Looking at repo with directory /Users/davsclaus/workspace/fabric8-forge/.git
[INFO] Looking at repo with directory /Users/davsclaus/workspace/fabric8-forge/.git
```

**Comment by davsclaus** [comment]
Ah am I using the old version with -  fabric8-maven-plugin:2.2.147:json

**Comment by rhuss** [comment]
There are several ways to tune it from the outside:

* There is a property called `fabric8.online` which by default is set when the `BUILD_ID` env is set, but explicitly set to `false`, too. Any enricher which requires live access to a cluster is disabled if this variable is not set. In your case I wonder why this error occurs which can be only possible if the online mode has been switched off.
* I will add a a fabric8 profile, lets call it 'minimal' to the plugin which then can be switched on with `-Dfabric8.profile=minimal` in which case only the enrichers configured in this profile are used. The challenge is to define meaningful profiles, which should cover certain use cases.

About the `.git` info message above, I don't think that it comes from f-m-p (at least I could not found it directly).

**Comment by rhuss** [comment]
ok, that explains a bit.

BTW, I would love to have a more unique indication when to switch on `live` mode. `BUILD_ID` is a bit weak, but dont know what is better to detect that we are indeed running as part of CD run. Any ideas ?

**Comment by rhuss** [comment]
See also #157 for some discussion around this.

**Comment by davsclaus** [comment]
I wonder if the logging can be prefixed with what enricher/customizer/etc is doing the logging, eg I see `F8>`

```
[info] F8> Adding a default Service with ports [8778]
[info] F8> Adding a default Deployment
[info] F8> Looking at repo with directory /Users/davsclaus/workspace/fabric8-forge/.git
[WARNING] Could not lookup service:gogs in namespace:default, due to: An error has occurred.
[INFO] Connecting to service gogs on : from $GOGS_SERVICE_HOST and $GOGS_SERVICE_PORT
[warn] F8> Failed: java.lang.IllegalArgumentException: No kubernetes service could be found for name: gogs in namespace: default
java.lang.IllegalArgumentException: No kubernetes service could be found for name: gogs in namespace: default
```

It could then be `F8-GitEnricher>` and so on. That will help users better understand the logging message. And trouble shooting.

**Comment by davsclaus** [comment]
I cannot exclude that online git stuff
``
      <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>fabric8-maven-plugin</artifactId>
        <version>${fabric8.maven.plugin.version}</version>
        <configuration>
          <customizer>
            <java.app.mainClass>org.apache.camel.cdi.Main</java.app.mainClass>
          </customizer>
          <enricher>
            <excludes>
              <exclude>f8-cd</exclude>
            </excludes>
          </enricher>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>resource</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

And it logs when running `mvn package`

```
davsclaus:/Users/davsclaus/workspace/fabric8-forge/fabric8-forge/target/createdProjects/cdi-camel-amq-archetype/my-cdi-camel-amq (master)/$ mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Fabric8 :: Quickstarts :: CDI :: Camel and ActiveMQ 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ my-cdi-camel-amq ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- fabric8-maven-plugin:3.0.28:resource (default) @ my-cdi-camel-amq ---
[info] F8> Adding a default Service with ports [8778]
[info] F8> Adding a default Deployment
[info] F8> Looking at repo with directory /Users/davsclaus/workspace/fabric8-forge/.git
[WARNING] Could not lookup service:gogs in namespace:default, due to: An error has occurred.
[INFO] Connecting to service gogs on : from $GOGS_SERVICE_HOST and $GOGS_SERVICE_PORT
[warn] F8> Failed: java.lang.IllegalArgumentException: No kubernetes service could be found for name: gogs in namespace: default
java.lang.IllegalArgumentException: No kubernetes service could be found for name: gogs in namespace: default
       	at io.fabric8.kubernetes.api.KubernetesHelper.getServiceURL(KubernetesHelper.java:1297)
       	at io.fabric8.kubernetes.api.KubernetesHelper.getServiceURL(KubernetesHelper.java:1259)
       	at io.fabric8.maven.enricher.git.GitEnricher.getAnnotations(GitEnricher.java:129)
       	at io.fabric8.maven.plugin.enricher.EnricherManager$Extractor$2.extract(EnricherManager.java:154)
       	at io.fabric8.maven.plugin.enricher.EnricherManager.extract(EnricherManager.java:130)
       	at io.fabric8.maven.plugin.enricher.EnricherManager.extractAnnotations(EnricherManager.java:120)
       	at io.fabric8.maven.plugin.enricher.MetadataEnricherVisitor.visit(MetadataEnricherVisitor.java:46)
       	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:70)
       	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:10)
       	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:67)
       	at io.fabric8.maven.plugin.enricher.EnricherManager.visit(EnricherManager.java:174)
       	at io.fabric8.maven.plugin.enricher.EnricherManager.enrichLabels(EnricherManager.java:71)
       	at io.fabric8.maven.plugin.ResourceMojo.generateKubernetesResources(ResourceMojo.java:366)
       	at io.fabric8.maven.plugin.ResourceMojo.execute(ResourceMojo.java:160)
       	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
       	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
       	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
       	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
       	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
       	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
       	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
       	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
       	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
       	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
       	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
       	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
       	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:483)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[warn] F8> No kubernetes service could be found for name: gogs in namespace: default
[warn] F8> Cannot find $BUILD_ID so must not be inside a Jenkins build
[info] F8> Looking at repo with directory /Users/davsclaus/workspace/fabric8-forge/.git
[WARNING] Could not lookup service:gogs in namespace:default, due to: An error has occurred.
[INFO] Connecting to service gogs on : from $GOGS_SERVICE_HOST and $GOGS_SERVICE_PORT
[warn] F8> Failed: java.lang.IllegalArgumentException: No kubernetes service could be found for name: gogs in namespace: default
java.lang.IllegalArgumentException: No kubernetes service could be found for name: gogs in namespace: default
       	at io.fabric8.kubernetes.api.KubernetesHelper.getServiceURL(KubernetesHelper.java:1297)
       	at io.fabric8.kubernetes.api.KubernetesHelper.getServiceURL(KubernetesHelper.java:1259)
       	at io.fabric8.maven.enricher.git.GitEnricher.getAnnotations(GitEnricher.java:129)
       	at io.fabric8.maven.plugin.enricher.EnricherManager$Extractor$2.extract(EnricherManager.java:154)
       	at io.fabric8.maven.plugin.enricher.EnricherManager.extract(EnricherManager.java:130)
       	at io.fabric8.maven.plugin.enricher.EnricherManager.extractAnnotations(EnricherManager.java:120)
       	at io.fabric8.maven.plugin.enricher.MetadataEnricherVisitor.visit(MetadataEnricherVisitor.java:46)
       	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:70)
       	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:10)
       	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:67)
       	at io.fabric8.maven.plugin.enricher.EnricherManager.visit(EnricherManager.java:174)
       	at io.fabric8.maven.plugin.enricher.EnricherManager.enrichLabels(EnricherManager.java:71)
       	at io.fabric8.maven.plugin.ResourceMojo.generateKubernetesResources(ResourceMojo.java:366)
       	at io.fabric8.maven.plugin.ResourceMojo.execute(ResourceMojo.java:160)
       	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
       	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
       	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
       	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
       	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
       	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
       	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
       	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
       	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
       	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
       	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
       	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
       	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:483)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[warn] F8> No kubernetes service could be found for name: gogs in namespace: default
[warn] F8> Cannot find $BUILD_ID so must not be inside a Jenkins build
```

**Comment by rhuss** [comment]
w.r.t to the log prefix: Which version are you using from f-m-p ? Because in the latest versions this is already included:

```
.....
[INFO] F8> f8-service: Adding a default Service with ports [8080]
[INFO] F8> f8-controller: Adding a default Deployment
```

**Comment by davsclaus** [comment]
fabric8-maven-plugin:3.0.28

Ah let me manually update it, I guess those fancy auto update versions dont always work.

3.1.10 is the latest version

**Comment by rhuss** [comment]
@davsclaus : btw, when you run with '-Dfabric8.verbose' you get the full list of enrichers and genertors which apply.

**Comment by davsclaus** [comment]
Argh its the archetypes that is outdated

**Comment by rhuss** [comment]
when you use a newer version you probably dont even need to exclude `f8-cd` since it then does some autodetection, too.

**Comment by davsclaus** [comment]
Yay it now runs in 5 sec instead of 30 or so

```
[INFO] --- fabric8-maven-plugin:3.1.10:resource (default) @ my-cdi-camel-amq ---
[INFO] F8> Running in Kubernetes mode
[INFO] F8> f8-controller: Adding a default Deployment
[ERROR] F8> Cannot extract Git information for adding to annotations: java.io.IOException: Systen wide config file /usr/local/git/etc/gitconfig is invalid org.eclipse.jgit.errors.ConfigInvalidException: Cannot read file /usr/local/git/etc/gitconfig
```

But there is a jgit error. I have seen some jgit error when Andrea attempted to update jgit for hawtio and it had some bugs there.

**Comment by rhuss** [comment]
@davsclaus could you please let it run with `-e` to see the full exception stack trace ?

**Comment by davsclaus** [comment]
There is no stacktrace logged, only that single line

**Comment by rhuss** [comment]
I upgraded jgit, hopefully the issue vanishes (btw, can't reproduce it here).

New f-m-p release comes soon.
