### ISSUE TITLE
Creating WildFly Swarm fails to run using the run-java.sh script

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-maven-plugin#320]
I created a wildfly-swarm application which I cannot run from docker or kubernetes when it was created using the f-m-p plugin.

If I manually start the docker container using `sh` (notice `bash` is not there) then I can make tha WildFly Swarm application start if I run it manually using

```
java -jar helloswarm-swarm.jar
```

But if I run the application using the start script

```
./run-java.sh
```

It fails.

I have pasted the output from the shell below:

```
/app # export
export HOME='/root'
export HOSTNAME='382f64c36855'
export JAVA_APP_DIR='/app'
export JAVA_DATA_DIR='/app/data'
export OLDPWD='/'
export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
export PWD='/app'
export SHLVL='1'
export TERM='xterm'
/app # ls
data                    helloswarm-swarm.jar    java-container-options  run-java.sh
/app # ls data/
/app # java -version
openjdk version "1.8.0_92-internal"
OpenJDK Runtime Environment (build 1.8.0_92-internal-alpine-r1-b14)
OpenJDK 64-Bit Server VM (build 25.92-b14, mixed mode)
/app # java -jar helloswarm-swarm.jar
10:34:36,068 INFO  [org.wildfly.swarm] (main) WFSWARM0018: Installed fraction:                Container - STABLE          org.wildfly.swarm:container:2016.9
10:34:36,110 INFO  [org.wildfly.swarm] (main) WFSWARM0018: Installed fraction:                  Logging - STABLE          org.wildfly.swarm:logging:2016.9
10:34:36,111 INFO  [org.wildfly.swarm] (main) WFSWARM0018: Installed fraction:          Bean Validation - STABLE          org.wildfly.swarm:bean-validation:2016.9
10:34:36,111 INFO  [org.wildfly.swarm] (main) WFSWARM0018: Installed fraction:                       IO - STABLE          org.wildfly.swarm:io:2016.9
10:34:36,113 INFO  [org.wildfly.swarm] (main) WFSWARM0018: Installed fraction:                   Naming - STABLE          org.wildfly.swarm:naming:2016.9
10:34:36,113 INFO  [org.wildfly.swarm] (main) WFSWARM0018: Installed fraction:       Request Controller - STABLE          org.wildfly.swarm:request-controller:2016.9
10:34:36,114 INFO  [org.wildfly.swarm] (main) WFSWARM0018: Installed fraction:             Transactions - STABLE          org.wildfly.swarm:transactions:2016.9
10:34:36,119 INFO  [org.wildfly.swarm] (main) WFSWARM0018: Installed fraction:                      CDI - STABLE          org.wildfly.swarm:cdi:2016.9
10:34:36,121 WARN  [org.wildfly.swarm] (main) WFSWARM0018: Installed fraction:                    Camel - UNSTABLE        org.wildfly.swarm:camel-core:2016.9
10:34:36,121 INFO  [org.wildfly.swarm] (main) WFSWARM0018: Installed fraction:                       EE - STABLE          org.wildfly.swarm:ee:2016.9
10:34:36,122 INFO  [org.wildfly.swarm] (main) WFSWARM0018: Installed fraction:                 Undertow - STABLE          org.wildfly.swarm:undertow:2016.9
10:34:36,282 INFO  [org.jboss.weld.Version] (main) WELD-000900: 3.0.0 (Alpha16)
10:34:36,332 INFO  [org.jboss.weld.Bootstrap] (main) WELD-ENV-000020: Using jandex for bean discovery
10:34:36,788 INFO  [org.jboss.weld.Bootstrap] (main) WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
10:34:36,913 WARN  [org.jboss.weld.Interceptor] (main) WELD-001700: Interceptor annotation class javax.ejb.PostActivate not found, interception based on it is not enabled
10:34:36,916 WARN  [org.jboss.weld.Interceptor] (main) WELD-001700: Interceptor annotation class javax.ejb.PrePassivate not found, interception based on it is not enabled
10:34:38,985 INFO  [org.jboss.weld.Bootstrap] (main) WELD-ENV-002003: Weld SE container STATIC_INSTANCE initialized
10:34:40,747 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.6.Final
10:34:41,007 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0049: WildFly Swarm 2016.9 (WildFly Core 2.2.0.Final) starting
10:34:41,100 INFO  [org.wildfly.swarm] (MSC service thread 1-2) WFSWARM0029: Install MSC service for command line args: []
2016-09-08 10:34:42,260 WARN  [org.jboss.as.txn] (ServerService Thread Pool -- 13) WFLYTX0013: Node identifier property is set to the default value. Please make sure it is unique.
2016-09-08 10:34:42,267 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 15) WFLYNAM0001: Activating Naming Subsystem
2016-09-08 10:34:42,705 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 19) WFLYIO001: Worker 'default' has auto-configured to 2 core threads with 16 task threads based on your 1 available processors
2016-09-08 10:34:42,736 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0003: Undertow 1.4.0.Final starting
2016-09-08 10:34:42,900 INFO  [org.jboss.as.naming] (MSC service thread 1-2) WFLYNAM0003: Starting Naming Service
2016-09-08 10:34:42,912 INFO  [org.jboss.gravia.runtime] (MSC service thread 1-1) Installed: Module[gravia-system:0.0.0]
2016-09-08 10:34:42,923 INFO  [org.jboss.gravia.runtime] (MSC service thread 1-1) Runtime created: org.wildfly.extension.gravia.service.WildFlyRuntime@27028a82
2016-09-08 10:34:43,020 INFO  [org.xnio] (MSC service thread 1-1) XNIO version 3.4.0.Final
2016-09-08 10:34:43,028 INFO  [org.xnio.nio] (MSC service thread 1-1) XNIO NIO Implementation Version 3.4.0.Final
2016-09-08 10:34:43,034 INFO  [org.wildfly.extension.camel] (MSC service thread 1-2) Activating Camel Subsystem
2016-09-08 10:34:43,129 INFO  [org.wildfly.extension.gravia] (MSC service thread 1-2) Activating Gravia Subsystem
2016-09-08 10:34:43,205 INFO  [org.jboss.gravia.runtime] (MSC service thread 1-2) Installed: Module[gravia-container-wildfly-extension:1.3.1]
2016-09-08 10:34:43,206 INFO  [org.jboss.gravia.runtime] (MSC service thread 1-2) Started: Module[gravia-container-wildfly-extension:1.3.1]
2016-09-08 10:34:43,242 INFO  [org.wildfly.extension.camel] (MSC service thread 1-2) Bound camel naming object: java:jboss/camel/CamelContextFactory
2016-09-08 10:34:43,250 INFO  [org.wildfly.extension.camel] (MSC service thread 1-2) Bound camel naming object: java:jboss/camel/CamelContextRegistry
2016-09-08 10:34:43,268 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0012: Started server default-server.
2016-09-08 10:34:43,289 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0018: Host default-host starting
2016-09-08 10:34:43,518 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0006: Undertow HTTP listener default listening on [0:0:0:0:0:0:0:0]:8080
2016-09-08 10:34:43,770 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Swarm 2016.9 (WildFly Core 2.2.0.Final) started in 3105ms - Started 93 of 100 services (19 services are lazy, passive or on-demand)
2016-09-08 10:34:44,138 INFO  [org.wildfly.swarm.runtime.deployer] (main) deploying helloswarm.war
2016-09-08 10:34:44,203 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0027: Starting deployment of "helloswarm.war" (runtime-name: "helloswarm.war")
2016-09-08 10:34:44,953 WARN  [org.jboss.weld.deployer] (MSC service thread 1-2) WFLYWELD0012: Warning while parsing vfs:/helloswarm.war/WEB-INF/classes/META-INF/beans.xml:2 cvc-elt.1.a: Cannot find the declaration of element 'beans'.
2016-09-08 10:34:45,081 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-2) WFLYSRV0018: Deployment "deployment.helloswarm.war" is using a private module ("org.jboss.jts:main") which may be changed or removed in future versions without notice.
2016-09-08 10:34:45,332 INFO  [org.jboss.weld.deployer] (MSC service thread 1-1) WFLYWELD0003: Processing weld deployment helloswarm.war
2016-09-08 10:34:45,473 WARN  [org.jboss.weld.deployer] (MSC service thread 1-1) WFLYWELD0012: Warning while parsing jar:file:/tmp/camel-cdi-2.17.25054791461461831119.jar!/META-INF/beans.xml:18 cvc-elt.1.a: Cannot find the declaration of element 'beans'.
2016-09-08 10:34:45,531 INFO  [org.hibernate.validator.internal.util.Version] (MSC service thread 1-1) HV000001: Hibernate Validator 5.2.4.Final
2016-09-08 10:34:46,049 INFO  [org.jboss.weld.Version] (MSC service thread 1-2) WELD-000900: 2.3.5 (Final)
2016-09-08 10:34:46,589 INFO  [org.jboss.weld.Event] (MSC service thread 1-2) WELD-000411: Observer method [BackedAnnotatedMethod] private org.apache.camel.cdi.CdiCamelExtension.processAnnotatedType(@Observes ProcessAnnotatedType<?>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2016-09-08 10:34:47,674 WARN  [org.jboss.as.weld] (MSC service thread 1-2) WFLYWELD0052: Using deployment classloader to load proxy classes for module org.apache.camel.core:main. Package-private access will not work. To fix this the module should declare dependencies on [org.jboss.weld.core, org.jboss.weld.spi]
2016-09-08 10:34:48,476 INFO  [org.apache.camel.impl.converter.DefaultTypeConverter] (MSC service thread 1-2) Loaded 200 type converters
2016-09-08 10:34:48,550 INFO  [org.apache.camel.cdi.CdiCamelExtension] (MSC service thread 1-2) Camel CDI is starting Camel context [camel-1]
2016-09-08 10:34:48,551 INFO  [org.apache.camel.impl.DefaultCamelContext] (MSC service thread 1-2) Apache Camel 2.17.2 (CamelContext: camel-1) is starting
2016-09-08 10:34:48,553 INFO  [org.apache.camel.management.ManagedManagementStrategy] (MSC service thread 1-2) JMX is enabled
2016-09-08 10:34:48,752 INFO  [org.wildfly.extension.camel] (MSC service thread 1-1) Bound camel naming object: java:jboss/camel/context/camel-1
2016-09-08 10:34:48,753 INFO  [org.wildfly.extension.camel] (MSC service thread 1-2) Camel context starting: camel-1
2016-09-08 10:34:48,848 INFO  [org.apache.camel.impl.DefaultRuntimeEndpointRegistry] (MSC service thread 1-2) Runtime endpoint registry is in extended mode gathering usage statistics of all incoming and outgoing endpoints (cache limit: 1000)
2016-09-08 10:34:48,988 INFO  [org.apache.camel.impl.DefaultCamelContext] (MSC service thread 1-2) AllowUseOriginalMessage is enabled. If access to the original message is not needed, then its recommended to turn this option off as it may improve performance.
2016-09-08 10:34:49,000 INFO  [org.apache.camel.impl.DefaultCamelContext] (MSC service thread 1-2) StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
2016-09-08 10:34:49,081 INFO  [org.apache.camel.component.undertow.UndertowRegistry] (MSC service thread 1-2) Adding consumer to consumerRegistry: http://localhost:8080/hello
2016-09-08 10:34:49,091 INFO  [org.wildfly.extension.camel] (MSC service thread 1-2) Add Camel endpoint: http://[::]:8080/hello
2016-09-08 10:34:49,092 INFO  [org.apache.camel.impl.DefaultCamelContext] (MSC service thread 1-2) Route: route1 started and consuming from: Endpoint[http://localhost:8080/hello]
2016-09-08 10:34:49,093 INFO  [org.apache.camel.impl.DefaultCamelContext] (MSC service thread 1-2) Total 1 routes, of which 1 are started.
2016-09-08 10:34:49,099 INFO  [org.apache.camel.impl.DefaultCamelContext] (MSC service thread 1-2) Apache Camel 2.17.2 (CamelContext: camel-1) started in 0.542 seconds
2016-09-08 10:34:49,409 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 21) WFLYUT0021: Registered web context: /
2016-09-08 10:34:49,412 INFO  [org.wildfly.extension.camel] (ServerService Thread Pool -- 21) Add Camel endpoint: http://[::]:8080
2016-09-08 10:34:49,422 INFO  [org.jboss.as.server] (main) WFLYSRV0010: Deployed "helloswarm.war" (runtime-name : "helloswarm.war")
^C2016-09-08 10:34:54,441 INFO  [org.jboss.as.server] (Thread-4) WFLYSRV0220: Server shutdown has been requested via an OS signal
2016-09-08 10:34:54,534 INFO  [org.wildfly.extension.camel] (ServerService Thread Pool -- 7) Remove Camel endpoint: http://[::]:8080
2016-09-08 10:34:54,537 INFO  [org.jboss.weld.Bootstrap] (Thread-3) WELD-ENV-002001: Weld SE container STATIC_INSTANCE shut down
2016-09-08 10:34:54,550 INFO  [stdout] (Thread-3) Weld SE container STATIC_INSTANCE shut down by shutdown hook
2016-09-08 10:34:54,552 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 7) WFLYUT0022: Unregistered web context: /
2016-09-08 10:34:54,561 INFO  [org.jboss.gravia.runtime] (MSC service thread 1-2) Stopped: Module[gravia-container-wildfly-extension:1.3.1]
2016-09-08 10:34:54,565 INFO  [org.jboss.gravia.runtime] (MSC service thread 1-2) Uninstalled: Module[gravia-container-wildfly-extension:1.3.1]
2016-09-08 10:34:54,569 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0008: Undertow HTTP listener default suspending
2016-09-08 10:34:54,581 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0007: Undertow HTTP listener default stopped, was bound to [0:0:0:0:0:0:0:0]:8080
2016-09-08 10:34:54,582 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0019: Host default-host stopping
2016-09-08 10:34:54,608 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0004: Undertow 1.4.0.Final stopping
2016-09-08 10:34:54,626 INFO  [org.apache.camel.cdi.CamelContextProducer] (MSC service thread 1-1) Camel CDI is stopping Camel context [camel-1]
2016-09-08 10:34:54,629 INFO  [org.apache.camel.impl.DefaultCamelContext] (MSC service thread 1-1) Apache Camel 2.17.2 (CamelContext: camel-1) is shutting down
2016-09-08 10:34:54,631 INFO  [org.apache.camel.impl.DefaultShutdownStrategy] (MSC service thread 1-1) Starting to graceful shutdown 1 routes (timeout 300 seconds)
2016-09-08 10:34:54,664 INFO  [org.wildfly.extension.camel] (Camel (camel-1) thread #0 - ShutdownTask) Remove Camel endpoint: http://[::]:8080/hello
2016-09-08 10:34:54,667 INFO  [org.apache.camel.impl.DefaultShutdownStrategy] (Camel (camel-1) thread #0 - ShutdownTask) Route: route1 shutdown complete, was consuming from: Endpoint[http://localhost:8080/hello]
2016-09-08 10:34:54,669 INFO  [org.apache.camel.impl.DefaultShutdownStrategy] (MSC service thread 1-1) Graceful shutdown of 1 routes completed in 0 seconds
2016-09-08 10:34:54,681 INFO  [org.wildfly.extension.camel] (MSC service thread 1-1) Camel context stopped: camel-1
2016-09-08 10:34:54,699 INFO  [org.apache.camel.impl.DefaultCamelContext] (MSC service thread 1-1) Apache Camel 2.17.2 (CamelContext: camel-1) uptime 6.148 seconds
2016-09-08 10:34:54,700 INFO  [org.apache.camel.impl.DefaultCamelContext] (MSC service thread 1-1) Apache Camel 2.17.2 (CamelContext: camel-1) is shutdown in 0.070 seconds
2016-09-08 10:34:54,751 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0028: Stopped deployment helloswarm.war (runtime-name: helloswarm.war) in 282ms
2016-09-08 10:34:54,756 INFO  [org.jboss.gravia.runtime] (MSC service thread 1-2) Runtime released: org.wildfly.extension.gravia.service.WildFlyRuntime@27028a82
2016-09-08 10:34:54,772 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0050: WildFly Swarm 2016.9 (WildFly Core 2.2.0.Final) stopped in 248ms
/app # ls
data                    helloswarm-swarm.jar    java-container-options  run-java.sh
/app # ./run-java.sh
I> No access restrictor found, access to any MBean is allowed
Jolokia: Agent started with URL http://172.17.0.3:8778/jolokia/
2016-09-08 10:34:59.138:INFO:ifasjipjsoejs.Server:jetty-8.y.z-SNAPSHOT
2016-09-08 10:34:59.189:INFO:ifasjipjsoejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:9779
Sep 08, 2016 10:35:01 AM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0018: Installed fraction:                Container - STABLE          org.wildfly.swarm:container:2016.9
Sep 08, 2016 10:35:01 AM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0018: Installed fraction:                  Logging - STABLE          org.wildfly.swarm:logging:2016.9
Sep 08, 2016 10:35:01 AM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0018: Installed fraction:          Bean Validation - STABLE          org.wildfly.swarm:bean-validation:2016.9
Sep 08, 2016 10:35:01 AM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0018: Installed fraction:                       IO - STABLE          org.wildfly.swarm:io:2016.9
Sep 08, 2016 10:35:01 AM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0018: Installed fraction:                   Naming - STABLE          org.wildfly.swarm:naming:2016.9
Sep 08, 2016 10:35:01 AM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0018: Installed fraction:       Request Controller - STABLE          org.wildfly.swarm:request-controller:2016.9
Sep 08, 2016 10:35:01 AM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0018: Installed fraction:             Transactions - STABLE          org.wildfly.swarm:transactions:2016.9
Sep 08, 2016 10:35:01 AM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0018: Installed fraction:                      CDI - STABLE          org.wildfly.swarm:cdi:2016.9
Sep 08, 2016 10:35:01 AM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
WARN: WFSWARM0018: Installed fraction:                    Camel - UNSTABLE        org.wildfly.swarm:camel-core:2016.9
Sep 08, 2016 10:35:01 AM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0018: Installed fraction:                       EE - STABLE          org.wildfly.swarm:ee:2016.9
Sep 08, 2016 10:35:01 AM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0018: Installed fraction:                 Undertow - STABLE          org.wildfly.swarm:undertow:2016.9
Sep 08, 2016 10:35:01 AM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 3.0.0 (Alpha16)
Sep 08, 2016 10:35:01 AM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Sep 08, 2016 10:35:02 AM org.jboss.weld.bootstrap.WeldStartup startContainer
INFO: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
Sep 08, 2016 10:35:02 AM org.jboss.weld.interceptor.util.InterceptionTypeRegistry <clinit>
WARN: WELD-001700: Interceptor annotation class javax.ejb.PostActivate not found, interception based on it is not enabled
Sep 08, 2016 10:35:02 AM org.jboss.weld.interceptor.util.InterceptionTypeRegistry <clinit>
WARN: WELD-001700: Interceptor annotation class javax.ejb.PrePassivate not found, interception based on it is not enabled
Sep 08, 2016 10:35:04 AM org.jboss.weld.environment.se.WeldContainer initialize
INFO: WELD-ENV-002003: Weld SE container STATIC_INSTANCE initialized
Sep 08, 2016 10:35:06 AM org.jboss.msc.service.ServiceContainerImpl <clinit>
INFO: JBoss MSC version 1.2.6.Final
Sep 08, 2016 10:35:06 AM org.jboss.as.server.ApplicationServerService start
INFO: WFLYSRV0049: WildFly Swarm 2016.9 (WildFly Core 2.2.0.Final) starting
Sep 08, 2016 10:35:06 AM org.wildfly.swarm.container.runtime.cli.CommandLineArgsServiceActivator activate
INFO: WFSWARM0029: Install MSC service for command line args: []
Sep 08, 2016 10:35:07 AM org.jboss.as.controller.AbstractOperationContext executeStep
ERROR: WFLYCTL0013: Operation ("parallel-extension-add") failed - address: ([])
java.lang.RuntimeException: WFLYCTL0079: Failed initializing module org.jboss.as.logging
        at org.jboss.as.controller.extension.ParallelExtensionAddHandler$1.execute(ParallelExtensionAddHandler.java:115)
        at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:890)
        at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:659)
        at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)
        at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1329)
        at org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:467)
        at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:387)
        at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:349)
        at org.jboss.as.server.ServerService.boot(ServerService.java:397)
        at org.jboss.as.server.ServerService.boot(ServerService.java:366)
        at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: WFLYLOG0078: The logging subsystem requires the log manager to be org.jboss.logmanager.LogManager. The subsystem has not be initialized and cannot be used. To use JBoss Log Manager you must add the system property "java.util.logging.manager" and set it to "org.jboss.logmanager.LogManager"
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.jboss.as.controller.extension.ParallelExtensionAddHandler$1.execute(ParallelExtensionAddHandler.java:107)
        ... 11 more
Caused by: java.lang.IllegalStateException: WFLYLOG0078: The logging subsystem requires the log manager to be org.jboss.logmanager.LogManager. The subsystem has not be initialized and cannot be used. To use JBoss Log Manager you must add the system property "java.util.logging.manager" and set it to "org.jboss.logmanager.LogManager"
        at org.jboss.as.logging.LoggingExtension.initialize(LoggingExtension.java:147)
        at org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:131)
        at org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:104)
        at org.jboss.as.controller.extension.ParallelExtensionAddHandler$ExtensionInitializeTask.call(ParallelExtensionAddHandler.java:144)
        at org.jboss.as.controller.extension.ParallelExtensionAddHandler$ExtensionInitializeTask.call(ParallelExtensionAddHandler.java:127)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at org.jboss.threads.JBossThread.run(JBossThread.java:320)

java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.wildfly.swarm.bootstrap.Main.invoke(Main.java:78)
        at org.wildfly.swarm.bootstrap.Main.run(Main.java:53)
        at org.wildfly.swarm.bootstrap.Main.main(Main.java:44)
Caused by: java.util.concurrent.ExecutionException: Operation failed
        at org.jboss.threads.AsyncFutureTask.operationFailed(AsyncFutureTask.java:74)
        at org.jboss.threads.AsyncFutureTask.get(AsyncFutureTask.java:268)
        at org.jboss.as.server.SelfContainedContainer.start(SelfContainedContainer.java:115)
        at org.wildfly.swarm.container.runtime.RuntimeServer.start(RuntimeServer.java:141)
        at org.wildfly.swarm.container.runtime.ServerBootstrapImpl.bootstrap(ServerBootstrapImpl.java:100)
        at org.wildfly.swarm.Swarm.start(Swarm.java:342)
        at org.wildfly.swarm.Swarm.start(Swarm.java:320)
        at org.wildfly.swarm.Swarm.main(Swarm.java:525)
        ... 7 more
Caused by: java.lang.Exception: WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
        at org.jboss.as.server.BootstrapListener.bootFailure(BootstrapListener.java:87)
        at org.jboss.as.server.ServerService.boot(ServerService.java:384)
        at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299)
        at java.lang.Thread.run(Thread.java:745)
Sep 08, 2016 10:35:07 AM org.jboss.as.server.ServerService$4 logExit
FATAL: WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.wildfly.swarm.bootstrap.Main.invoke(Main.java:78)
        at org.wildfly.swarm.bootstrap.Main.run(Main.java:53)
        at org.wildfly.swarm.bootstrap.Main.main(Main.java:44)
Caused by: java.util.concurrent.ExecutionException: Operation failed
        at org.jboss.threads.AsyncFutureTask.operationFailed(AsyncFutureTask.java:74)
        at org.jboss.threads.AsyncFutureTask.get(AsyncFutureTask.java:268)
        at org.jboss.as.server.SelfContainedContainer.start(SelfContainedContainer.java:115)
        at org.wildfly.swarm.container.runtime.RuntimeServer.start(RuntimeServer.java:141)
        at org.wildfly.swarm.container.runtime.ServerBootstrapImpl.bootstrap(ServerBootstrapImpl.java:100)
        at org.wildfly.swarm.Swarm.start(Swarm.java:342)
        at org.wildfly.swarm.Swarm.start(Swarm.java:320)
        at org.wildfly.swarm.Swarm.main(Swarm.java:525)
        ... 7 more
Caused by: java.lang.Exception: WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
        at org.jboss.as.server.BootstrapListener.bootFailure(BootstrapListener.java:87)
        at org.jboss.as.server.ServerService.boot(ServerService.java:384)
        at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299)
        at java.lang.Thread.run(Thread.java:745)
Weld SE container STATIC_INSTANCE shut down by shutdown hook
/app #
```

**Comment by davsclaus** [comment]
So its something in the run-java.sh script that setup something that causes WildFly Swarm to fail to start.

**Comment by davsclaus** [comment]
I wonder if its agent bond or something JVM agent that affect this?

**Comment by rhuss** [comment]
That's a known issue with wildfly-swarm and Jolokia. There are some fixed pending but not yet resolved.

* https://github.com/rhuss/jolokia/pull/260 is  a PR which I still need to integrate
* https://issues.jboss.org/browse/SWARM-204 is the corresponding issue in the swarm tracker.

I will try to integrate the PR to finally solve the issue (which btw imo should be fixed by swarm itself)

**Comment by christian-posta** [comment]
To work around this, turn Agent Bond off for the moment. With f-m-p if you include a snippet for the deployment.yml it can look like this:

```

spec:
  template:
    spec:
      containers:
      - env:
        - name: "AB_OFF"
          value: "true"
```

**Comment by davsclaus** [comment]
@cmoulliard here is more details about this logging issue on WF-Swarm
