### ISSUE TITLE
Message: DeploymentConfig "simple-config-map" is invalid: spec.template.metadata.labels: Invalid value: {"component":"simple-config-map

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-maven-plugin#367]
Hi,

When I run this maven cmd using version 3.1.42 on this project: https://github.com/redhat-microservices/quick_vertx_kube-configmap/blob/migrate-to-new-f8-plugin/pom.xml

```
mvn fabric8:resource fabric8:deploy
```

I get this error

```
 mvn fabric8:resource fabric8:deploy
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Quickstart :: Vert.x :: Simple Rest - Kubernetes ConfigMap 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- fabric8-maven-plugin:3.1.42:resource (default-cli) @ simple-config-map ---
[INFO] F8> Running in Kubernetes mode
[INFO] F8> Running generator java-exec
[INFO] F8> Using resource templates from /Users/chmoulli/Google-Drive/REDHAT/RH-GP/Projects/redhat-microservices/quick_vertx_kube-configmap/src/main/fabric8
[INFO] 
[INFO] --- fabric8-maven-plugin:3.1.42:deploy (default-cli) @ simple-config-map ---
[INFO] F8> Using OpenShift at https://192.168.64.13:8443/ in namespace default with manifest /Users/chmoulli/Google-Drive/REDHAT/RH-GP/Projects/redhat-microservices/quick_vertx_kube-configmap/target/classes/META-INF/fabric8/openshift.yml 
[INFO] OpenShift platform detected
[INFO] Using project: default
[INFO] Creating a Service from openshift.yml namespace default name simple-vertx-configmap
[INFO] Created Service: target/fabric8/applyJson/default/service-simple-vertx-configmap.json
[INFO] Creating a DeploymentConfig from openshift.yml namespace default name simple-config-map
[ERROR] Failed to create DeploymentConfig from openshift.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.64.13:8443/oapi/v1/namespaces/default/deploymentconfigs. Message: DeploymentConfig "simple-config-map" is invalid: spec.template.metadata.labels: Invalid value: {"component":"simple-config-map","container":"vertx","expose":"true","group":"vertx-demo","project":"simple-config-map","provider":"fabric8","version":"1.0.0-SNAPSHOT"}: `selector` does not match template `labels`. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.template.metadata.labels, message=Invalid value: {"component":"simple-config-map","container":"vertx","expose":"true","group":"vertx-demo","project":"simple-config-map","provider":"fabric8","version":"1.0.0-SNAPSHOT"}: `selector` does not match template `labels`, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=DeploymentConfig, name=simple-config-map, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=DeploymentConfig "simple-config-map" is invalid: spec.template.metadata.labels: Invalid value: {"component":"simple-config-map","container":"vertx","expose":"true","group":"vertx-demo","project":"simple-config-map","provider":"fabric8","version":"1.0.0-SNAPSHOT"}: `selector` does not match template `labels`, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).. DeploymentConfig(apiVersion=v1, kind=DeploymentConfig, metadata=ObjectMeta(annotations={fabric8.io/git-commit=0c7b2edfc317223fa8f2f19973992c048f73aecb, fabric8.io/iconUrl=img/icons/vertx.svg, fabric8.io/git-branch=migrate-to-new-f8-plugin, fabric8.io/metrics-path=dashboard/file/kubernetes-pods.json/?var-project=simple-config-map&var-version=1.0.0-SNAPSHOT}, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, generateName=null, generation=null, labels={container=vertx, component=simple-config-map, provider=fabric8, project=simple-config-map, expose=true, version=1.0.0-SNAPSHOT, group=vertx-demo}, name=simple-config-map, namespace=null, resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=DeploymentConfigSpec(replicas=1, selector={container=vertx, component=simple-config-map, provider=fabric8, project=simple-config-map, expose=true, group=io.vertx.example.kubernetes}, strategy=DeploymentStrategy(annotations=null, customParams=null, labels=null, recreateParams=null, resources=null, rollingParams=RollingDeploymentStrategyParams(intervalSeconds=null, maxSurge=null, maxUnavailable=null, post=null, pre=null, timeoutSeconds=10800, updatePercent=null, updatePeriodSeconds=null, additionalProperties={}), type=Rolling, additionalProperties={}), template=PodTemplateSpec(metadata=ObjectMeta(annotations={fabric8.io/git-commit=0c7b2edfc317223fa8f2f19973992c048f73aecb, fabric8.io/iconUrl=img/icons/vertx.svg, fabric8.io/git-branch=migrate-to-new-f8-plugin, fabric8.io/metrics-path=dashboard/file/kubernetes-pods.json/?var-project=simple-config-map&var-version=1.0.0-SNAPSHOT}, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, generateName=null, generation=null, labels={container=vertx, component=simple-config-map, provider=fabric8, project=simple-config-map, expose=true, version=1.0.0-SNAPSHOT, group=vertx-demo}, name=null, namespace=null, resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, containers=[Container(args=[], command=[], env=[EnvVar(name=KUBERNETES_NAMESPACE, value=null, valueFrom=EnvVarSource(configMapKeyRef=null, fieldRef=ObjectFieldSelector(apiVersion=null, fieldPath=metadata.namespace, additionalProperties={}), secretKeyRef=null, additionalProperties={}), additionalProperties={})], image=vertx-demo/simple-config-map:1.0.0-SNAPSHOT, imagePullPolicy=IfNotPresent, lifecycle=null, livenessProbe=null, name=simple-config-map, ports=[], readinessProbe=null, resources=ResourceRequirements(limits={cpu=Quantity(amount=0, format=null, additionalProperties={}), memory=Quantity(amount=0, format=null, additionalProperties={})}, requests={cpu=Quantity(amount=0, format=null, additionalProperties={}), memory=Quantity(amount=0, format=null, additionalProperties={})}, additionalProperties={}), securityContext=SecurityContext(capabilities=null, privileged=false, readOnlyRootFilesystem=null, runAsNonRoot=null, runAsUser=null, seLinuxOptions=null, additionalProperties={}), stdin=null, stdinOnce=null, terminationMessagePath=null, tty=null, volumeMounts=[], workingDir=null, additionalProperties={})], dnsPolicy=null, host=null, hostIPC=null, hostNetwork=null, hostPID=null, imagePullSecrets=[], nodeName=null, nodeSelector=null, restartPolicy=null, securityContext=null, serviceAccount=null, serviceAccountName=null, terminationGracePeriodSeconds=null, volumes=[], additionalProperties={}), additionalProperties={}), test=null, triggers=[DeploymentTriggerPolicy(imageChangeParams=null, type=ConfigChange, additionalProperties={})], additionalProperties={}), status=null, additionalProperties={})
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.64.13:8443/oapi/v1/namespaces/default/deploymentconfigs. Message: DeploymentConfig "simple-config-map" is invalid: spec.template.metadata.labels: Invalid value: {"component":"simple-config-map","container":"vertx","expose":"true","group":"vertx-demo","project":"simple-config-map","provider":"fabric8","version":"1.0.0-SNAPSHOT"}: `selector` does not match template `labels`. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.template.metadata.labels, message=Invalid value: {"component":"simple-config-map","container":"vertx","expose":"true","group":"vertx-demo","project":"simple-config-map","provider":"fabric8","version":"1.0.0-SNAPSHOT"}: `selector` does not match template `labels`, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=DeploymentConfig, name=simple-config-map, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=DeploymentConfig "simple-config-map" is invalid: spec.template.metadata.labels: Invalid value: {"component":"simple-config-map","container":"vertx","expose":"true","group":"vertx-demo","project":"simple-config-map","provider":"fabric8","version":"1.0.0-SNAPSHOT"}: `selector` does not match template `labels`, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:314)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:267)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:236)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:229)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:207)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:547)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:243)
        at io.fabric8.kubernetes.api.Controller.doCreateResource(Controller.java:938)
        at io.fabric8.kubernetes.api.Controller.applyResource(Controller.java:927)
        at io.fabric8.kubernetes.api.Controller.applyEntity(Controller.java:255)
        at io.fabric8.kubernetes.api.Controller.apply(Controller.java:231)
        at io.fabric8.maven.plugin.DeployMojo.applyEntities(DeployMojo.java:299)
        at io.fabric8.maven.plugin.DeployMojo.executeInternal(DeployMojo.java:266)
        at io.fabric8.maven.plugin.AbstractFabric8Mojo.execute(AbstractFabric8Mojo.java:49)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.816 s
[INFO] Finished at: 2016-09-16T19:05:17+02:00
[INFO] Final Memory: 30M/378M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.42:deploy (default-cli) on project simple-config-map: Failed to create DeploymentConfig from openshift.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.64.13:8443/oapi/v1/namespaces/default/deploymentconfigs. Message: DeploymentConfig "simple-config-map" is invalid: spec.template.metadata.labels: Invalid value: {"component":"simple-config-map","container":"vertx","expose":"true","group":"vertx-demo","project":"simple-config-map","provider":"fabric8","version":"1.0.0-SNAPSHOT"}: `selector` does not match template `labels`. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.template.metadata.labels, message=Invalid value: {"component":"simple-config-map","container":"vertx","expose":"true","group":"vertx-demo","project":"simple-config-map","provider":"fabric8","version":"1.0.0-SNAPSHOT"}: `selector` does not match template `labels`, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=DeploymentConfig, name=simple-config-map, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=DeploymentConfig "simple-config-map" is invalid: spec.template.metadata.labels: Invalid value: {"component":"simple-config-map","container":"vertx","expose":"true","group":"vertx-demo","project":"simple-config-map","provider":"fabric8","version":"1.0.0-SNAPSHOT"}: `selector` does not match template `labels`, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).. DeploymentConfig(apiVersion=v1, kind=DeploymentConfig, metadata=ObjectMeta(annotations={fabric8.io/git-commit=0c7b2edfc317223fa8f2f19973992c048f73aecb, fabric8.io/iconUrl=img/icons/vertx.svg, fabric8.io/git-branch=migrate-to-new-f8-plugin, fabric8.io/metrics-path=dashboard/file/kubernetes-pods.json/?var-project=simple-config-map&var-version=1.0.0-SNAPSHOT}, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, generateName=null, generation=null, labels={container=vertx, component=simple-config-map, provider=fabric8, project=simple-config-map, expose=true, version=1.0.0-SNAPSHOT, group=vertx-demo}, name=simple-config-map, namespace=null, resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=DeploymentConfigSpec(replicas=1, selector={container=vertx, component=simple-config-map, provider=fabric8, project=simple-config-map, expose=true, group=io.vertx.example.kubernetes}, strategy=DeploymentStrategy(annotations=null, customParams=null, labels=null, recreateParams=null, resources=null, rollingParams=RollingDeploymentStrategyParams(intervalSeconds=null, maxSurge=null, maxUnavailable=null, post=null, pre=null, timeoutSeconds=10800, updatePercent=null, updatePeriodSeconds=null, additionalProperties={}), type=Rolling, additionalProperties={}), template=PodTemplateSpec(metadata=ObjectMeta(annotations={fabric8.io/git-commit=0c7b2edfc317223fa8f2f19973992c048f73aecb, fabric8.io/iconUrl=img/icons/vertx.svg, fabric8.io/git-branch=migrate-to-new-f8-plugin, fabric8.io/metrics-path=dashboard/file/kubernetes-pods.json/?var-project=simple-config-map&var-version=1.0.0-SNAPSHOT}, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, generateName=null, generation=null, labels={container=vertx, component=simple-config-map, provider=fabric8, project=simple-config-map, expose=true, version=1.0.0-SNAPSHOT, group=vertx-demo}, name=null, namespace=null, resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, containers=[Container(args=[], command=[], env=[EnvVar(name=KUBERNETES_NAMESPACE, value=null, valueFrom=EnvVarSource(configMapKeyRef=null, fieldRef=ObjectFieldSelector(apiVersion=null, fieldPath=metadata.namespace, additionalProperties={}), secretKeyRef=null, additionalProperties={}), additionalProperties={})], image=vertx-demo/simple-config-map:1.0.0-SNAPSHOT, imagePullPolicy=IfNotPresent, lifecycle=null, livenessProbe=null, name=simple-config-map, ports=[], readinessProbe=null, resources=ResourceRequirements(limits={cpu=Quantity(amount=0, format=null, additionalProperties={}), memory=Quantity(amount=0, format=null, additionalProperties={})}, requests={cpu=Quantity(amount=0, format=null, additionalProperties={}), memory=Quantity(amount=0, format=null, additionalProperties={})}, additionalProperties={}), securityContext=SecurityContext(capabilities=null, privileged=false, readOnlyRootFilesystem=null, runAsNonRoot=null, runAsUser=null, seLinuxOptions=null, additionalProperties={}), stdin=null, stdinOnce=null, terminationMessagePath=null, tty=null, volumeMounts=[], workingDir=null, additionalProperties={})], dnsPolicy=null, host=null, hostIPC=null, hostNetwork=null, hostPID=null, imagePullSecrets=[], nodeName=null, nodeSelector=null, restartPolicy=null, securityContext=null, serviceAccount=null, serviceAccountName=null, terminationGracePeriodSeconds=null, volumes=[], additionalProperties={}), additionalProperties={}), test=null, triggers=[DeploymentTriggerPolicy(imageChangeParams=null, type=ConfigChange, additionalProperties={})], additionalProperties={}), status=null, additionalProperties={}) -> [Help 1]
[ERROR] 
```

Remark: I suspect that the json files created during the migration process from 2 to 3 are broken.

**Comment by cmoulliard** [comment]
Apparently, that works if I comment the group --> 

```
spec:
  replicas: 1
  template:
    metadata:
      labels:
        container: "vertx"
        component: "simple-config-map"
        provider: "fabric8"
        project: "${project.artifactId}"
        expose: "true"
        version: "${project.version}"
#        group: "vertx-demo"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "vertx-demo/simple-config-map:${project.version}"
        name: "simple-config-map"
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
```
