### ISSUE TITLE
Stream Closed : io.fabric8.openshift.client.dsl.internal.BuildConfigOperationsImpl

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-maven-plugin#380]
When I run this maven command 

```
mvn clean fabric8:run -Dfabric8.mode=openshift
```

to use OpenShift as deploy mode and behind the scene generate a BuildConfig & ImageStream files, I get this error 

https://gist.github.com/cmoulliard/dcc9fc70c69ff2b9ccc426d87d43d3a0#file-gistfile1-txt-L48

Pom of the project used : https://github.com/redhat-microservices/quick_vertx_kube-configmap/tree/migrate-to-new-f8-plugin

**Comment by rhuss** [comment]
It would be helpful to have the status of the corresponding OpenShift objects, e.g.

```
oc get bc
oc get build
oc get is
```

(same with `describe`).

This would help to debug this specific error. However, your setup won't work with an `buildStrategy` of **s2i** because for this you would need to specify a S2I builder image in the image's `<from>` configuration. You can still use `fabric8.mode=openshift` but with a build strategy **docker**. i.e. you should add `fabric8.build.strategy=docker`. See https://maven.fabric8.io/#fabric8:build

**Comment by cmoulliard** [comment]
The error is gone with a test performed on minishift provisioned with Fabric8. 

I will make a new test using a plain minishift instance created with the docker registry & router --> `minishift start --deploy-registry=true --deploy-router=true --memory=4048 --vm-driver="xhyve"`

**Comment by cmoulliard** [comment]
Here is the output generated after a new test performed with minishift where gofabric8 isn't deployed (I'm curious to know what is different between minishift alone and minishift + fabric8 !)

```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.42:build (fabric8) on project simple-config-map: Execution fabric8 of goal io.fabric8:fabric8-maven-plugin:3.1.42:build failed: An error has occurred. timeout: Read timed out -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
## Call REST endpoint
Error getting simple-vertx-configmap service: services "simple-vertx-configmap" not found
Check that minishift is running and that you have specified the correct namespace (-n flag).

http: error: InvalidURL: Invalid URL 'http:///products': No host supplied
dabou-macosx:~/RedHat/GP/projects/redhat-microservices/quick_vertx_kube-configmap$ oc get bc
NAME                TYPE      FROM      LATEST
simple-config-map   Source    Binary    1
dabou-macosx:~/RedHat/GP/projects/redhat-microservices/quick_vertx_kube-configmap$ oc get build
NAME                  TYPE      FROM      STATUS    STARTED         DURATION
simple-config-map-1   Source    Binary    Failed    8 minutes ago   25s
dabou-macosx:~/RedHat/GP/projects/redhat-microservices/quick_vertx_kube-configmap$ oc get is
NAME                DOCKER REPO                                        TAGS      UPDATED
simple-config-map   172.30.158.110:5000/vertx-demo/simple-config-map   
```

If I do again `mvn fabric8:run -Dfabric8.mode=openshift` then the Strem error is reported 

```
Caused by: java.io.IOException: Stream Closed
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:255)
        at okio.Okio$2.read(Okio.java:138)
        at okio.RealBufferedSink.writeAll(RealBufferedSink.java:97)
        at io.fabric8.openshift.client.dsl.internal.BuildConfigOperationsImpl$1.writeTo(BuildConfigOperationsImpl.java:231)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:47)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:65)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at io.fabric8.kubernetes.client.utils.HttpClientUtils$3.intercept(HttpClientUtils.java:102)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
        at okhttp3.RealCall.execute(RealCall.java:60)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:234)
        at io.fabric8.openshift.client.dsl.internal.BuildConfigOperationsImpl.fromInputStream(BuildConfigOperationsImpl.java:243)
        ... 34 more

and

oc get bc
NAME                TYPE      FROM      LATEST
simple-config-map   Source    Binary    3
dabou-macosx:~/RedHat/GP/projects/redhat-microservices/quick_vertx_kube-configmap$ oc get build
NAME                  TYPE      FROM      STATUS    STARTED          DURATION
simple-config-map-1   Source    Binary    Failed    13 minutes ago   25s
simple-config-map-2   Source    Binary    Failed                     
simple-config-map-3   Source    Binary    Failed                     
dabou-macosx:~/RedHat/GP/projects/redhat-microservices/quick_vertx_kube-configmap$ oc get is
NAME                DOCKER REPO                                        TAGS      UPDATED
simple-config-map   172.30.158.110:5000/vertx-demo/simple-config-map             

```

Project that you can use to reproduce is available here : https://github.com/redhat-microservices/quick_vertx_kube-configmap/tree/migrate-to-new-f8-plugin

**Comment by hodrigohamalho** [comment]
same error here.
