### ISSUE TITLE
WebAppGenerator throws IllegalStateException on initial build

### ISSUE THREAD

**Issue by jamesnetherton** [fabric8io/fabric8-maven-plugin#492]
With the latest SNAPSHOT I just tried:

```
mvn io.fabric8:fabric8-maven-plugin:3.1-SNAPSHOT:setup
mvn clean install
```

Which results in:

```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1-SNAPSHOT:resource (fmp) on project fmp-test: Execution fmp of goal io.fabric8:fabric8-maven-plugin:3.1-SNAPSHOT:resource failed: Cannot load service io.fabric8.maven.generator.webapp.WebAppGenerator defined in jar:file:/home/james/.m2/repository/io/fabric8/fabric8-maven-generator-webapp/3.1-SNAPSHOT/fabric8-maven-generator-webapp-3.1-SNAPSHOT.jar!/META-INF/fabric8/generator-default : java.lang.reflect.InvocationTargetException. Aborting: basedir /home/james/Spike/fmp-test/target/classes does not exist -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1-SNAPSHOT:resource (fmp) on project fmp-test: Execution fmp of goal io.fabric8:fabric8-maven-plugin:3.1-SNAPSHOT:resource failed: Cannot load service io.fabric8.maven.generator.webapp.WebAppGenerator defined in jar:file:/home/james/.m2/repository/io/fabric8/fabric8-maven-generator-webapp/3.1-SNAPSHOT/fabric8-maven-generator-webapp-3.1-SNAPSHOT.jar!/META-INF/fabric8/generator-default : java.lang.reflect.InvocationTargetException. Aborting
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution fmp of goal io.fabric8:fabric8-maven-plugin:3.1-SNAPSHOT:resource failed: Cannot load service io.fabric8.maven.generator.webapp.WebAppGenerator defined in jar:file:/home/james/.m2/repository/io/fabric8/fabric8-maven-generator-webapp/3.1-SNAPSHOT/fabric8-maven-generator-webapp-3.1-SNAPSHOT.jar!/META-INF/fabric8/generator-default : java.lang.reflect.InvocationTargetException. Aborting
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.IllegalStateException: Cannot load service io.fabric8.maven.generator.webapp.WebAppGenerator defined in jar:file:/home/james/.m2/repository/io/fabric8/fabric8-maven-generator-webapp/3.1-SNAPSHOT/fabric8-maven-generator-webapp-3.1-SNAPSHOT.jar!/META-INF/fabric8/generator-default : java.lang.reflect.InvocationTargetException. Aborting
	at io.fabric8.maven.core.util.PluginServiceFactory.readServiceDefinitionFromUrl(PluginServiceFactory.java:104)
	at io.fabric8.maven.core.util.PluginServiceFactory.readServiceDefinitions(PluginServiceFactory.java:88)
	at io.fabric8.maven.core.util.PluginServiceFactory.createServiceObjects(PluginServiceFactory.java:73)
	at io.fabric8.maven.plugin.generator.GeneratorManager.generate(GeneratorManager.java:58)
	at io.fabric8.maven.plugin.ResourceMojo$3.customizeConfig(ResourceMojo.java:584)
	at io.fabric8.maven.docker.config.ConfigHelper.resolveImages(ConfigHelper.java:51)
	at io.fabric8.maven.plugin.ResourceMojo.getResolvedImages(ResourceMojo.java:570)
	at io.fabric8.maven.plugin.ResourceMojo.executeInternal(ResourceMojo.java:233)
	at io.fabric8.maven.plugin.AbstractFabric8Mojo.execute(AbstractFabric8Mojo.java:61)
	at io.fabric8.maven.plugin.ResourceMojo.execute(ResourceMojo.java:225)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.fabric8.maven.core.util.PluginServiceFactory.createOrRemoveService(PluginServiceFactory.java:139)
	at io.fabric8.maven.core.util.PluginServiceFactory.readServiceDefinitionFromUrl(PluginServiceFactory.java:100)
	... 31 more
Caused by: java.lang.IllegalStateException: basedir /home/james/Spike/fmp-test/target/classes does not exist
	at org.apache.maven.shared.utils.io.DirectoryScanner.scan(DirectoryScanner.java:384)
	at io.fabric8.maven.generator.webapp.handler.AbstractAppServerHandler.scanFiles(AbstractAppServerHandler.java:29)
	at io.fabric8.maven.generator.webapp.handler.AbstractAppServerHandler.hasOneOf(AbstractAppServerHandler.java:40)
	at io.fabric8.maven.generator.webapp.handler.JettyAppSeverHandler.isApplicable(JettyAppSeverHandler.java:23)
	at io.fabric8.maven.generator.webapp.AppServerDetector.detect(AppServerDetector.java:32)
	at io.fabric8.maven.generator.webapp.WebAppGenerator.<init>(WebAppGenerator.java:67)
	... 37 more
```

**Comment by kameshsampath** [comment]
Resolved via pull #493
