### ISSUE TITLE
Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.69:cluster-start (default-cli) on project war -camel-servlet: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:3.1.69:cluster-start failed: Conversion = 'P'

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#553]
```
c:\fabric8\war-camel-servlet-master>mvn -e fabric8:cluster-start
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Fabric8 :: Quickstarts :: War :: Camel Servlet 2.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- fabric8-maven-plugin:3.1.69:cluster-start (default-cli) @ war-camel-servlet ---
[INFO] F8: Downloading version 0.4.78 of gofabric8 to C:\Users\guha\.fabric8\bin\gofabric8 ...
[INFO] F8: Running command gofabric8 C:\Temp\fabric85742212223540439980.bin version --batch
[INFO] F8:gofabric8 gofabric8, version 0.4.78 (branch: 'master', revision: '4d06bce')
[INFO] F8:gofabric8   build date:       '20161010-05:00:05'
[INFO] F8:gofabric8   go version:       '1.7.1'
[INFO] F8: Downloaded gofabric8 version 0.4.78 platform: windows arch:amd64 on: Windows 7 amd64 to: C:\Users\guha\.fabric8\bin\gofabric8
[WARNING] F8: Note that the fabric8 folder C:\Users\guha\.fabric8\bin is not on the PATH!
[WARNING] F8: Please add the following to PATH environment variable:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.263 s
[INFO] Finished at: 2016-10-11T17:52:37-05:00
[INFO] Final Memory: 21M/320M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.69:cluster-start (default-cli) on project war-camel-servlet: Execution default-cli of goal io
.fabric8:fabric8-maven-plugin:3.1.69:cluster-start failed: Conversion = 'P' -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.69:cluster-start (default-cli) on project war
-camel-servlet: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:3.1.69:cluster-start failed: Conversion = 'P'
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:3.1.69:cluster-start failed: Conversi
on = 'P'
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.util.UnknownFormatConversionException: Conversion = 'P'
        at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2691)
        at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2720)
        at java.util.Formatter.parse(Formatter.java:2560)
        at java.util.Formatter.format(Formatter.java:2501)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2927)
        at io.fabric8.maven.docker.util.AnsiLogger.colored(AnsiLogger.java:224)
        at io.fabric8.maven.docker.util.AnsiLogger.warn(AnsiLogger.java:88)
        at io.fabric8.maven.plugin.AbstractInstallMojo.installBinaries(AbstractInstallMojo.java:85)
        at io.fabric8.maven.plugin.ClusterStartMojo.executeInternal(ClusterStartMojo.java:55)
        at io.fabric8.maven.plugin.AbstractFabric8Mojo.execute(AbstractFabric8Mojo.java:71)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by rhuss** [comment]
Will fix this. Solution for such is always simple: Use `log.info("%s",line)` instead of `log.info(line)` for external input.

**Comment by rhuss** [comment]
btw, could probably be already fixed since I was cleaning up there yesterday (also checking this part), and currently cant map the exception anymore to the source.

**Comment by jstrachan** [comment]
ah great - sorry its all my fault! I was gonna go through and check all .info() and .warn() to check we always use the log.("%s", line) version

**Comment by jstrachan** [comment]
FWIW I think this one is now fixed in the latest release
