### ISSUE TITLE
Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.74:cluster-start (default-cli) on project standalone-pom: Failed to execute gofabric8.exestart --console --batch result was: 1

### ISSUE THREAD

**Issue by vaskrist** [fabric8io/fabric8-maven-plugin#572]
After using the plugin 3.1.69 and failing with #553 I used the latest version and failed with a similar error.

d:\temp\fabric>mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Java version: 1.8.0_92, vendor: Oracle Corporation
Default locale: cs_CZ, platform encoding: Cp1250
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"

d:\temp\fabric>mvn io.fabric8:fabric8-maven-plugin:3.1.74:cluster-start
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- fabric8-maven-plugin:3.1.74:cluster-start (default-cli) @ standalone-pom ---
[WARNING] F8: The fabric8 bin folder C:\Users\XXX\.fabric8\bin is not on the PATH.
[WARNING] F8: To easily start fabric8 CLI tools like gofabric8 directly, please adapt your environment:
[INFO] F8: Please add the following to your ~/.bashrc:
[INFO] F8:   export PATH=$PATH:C:\Users\XXX\.fabric8\bin
[INFO] F8: Running C:\Users\XXX\.fabric8\bin\gofabric8.exe start --console --batch
[INFO] F8:gofabric8 Downloading https://storage.googleapis.com/minikube/releases/v0.11.0/minikube-windows-amd64.exe...
[INFO] F8:gofabric8 Downloaded minikube.exe
[INFO] F8:gofabric8 Downloading https://storage.googleapis.com/kubernetes-release/release/v1.4.3/bin/windows/amd64/kubectl.exe...
[INFO] F8:gofabric8 Downloaded kubectl.exe
[INFO] F8:gofabric8 using the executable minikube.exe
Exception in thread "[OUT] gofabric8.exe start --console --batch" java.util.UnknownFormatConversionException: Conversion = 'P'
        at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2691)
        at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2720)
        at java.util.Formatter.parse(Formatter.java:2560)
        at java.util.Formatter.format(Formatter.java:2501)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at io.fabric8.maven.docker.util.AnsiLogger.colored(AnsiLogger.java:224)
        at io.fabric8.maven.docker.util.AnsiLogger.info(AnsiLogger.java:76)
        at io.fabric8.maven.core.util.ProcessUtil$4.apply(ProcessUtil.java:208)
        at io.fabric8.maven.core.util.ProcessUtil$4.apply(ProcessUtil.java:205)
        at io.fabric8.maven.core.util.ProcessUtil.processOutput(ProcessUtil.java:130)
        at io.fabric8.maven.core.util.ProcessUtil.access$100(ProcessUtil.java:34)
       at io.fabric8.maven.core.util.ProcessUtil$3.run(ProcessUtil.java:194)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.465 s
[INFO] Finished at: 2016-10-19T01:09:14+02:00
[INFO] Final Memory: 23M/224M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.74:cluster-start (default-cli) on project standalone-pom: Failed to execute gofabric8.exestart --console --batch result was: 1 -> [Help 1]   
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by jstrachan** [comment]
I think this has been fixed in version 3.1.74 of fabric8-maven-plugin

**Comment by vaskrist** [comment]
I have retried it after deleting the .fabric8 folder to avoid reuse and it worked fine.

**Comment by jstrachan** [comment]
@vaskrist awesome thats great to know!
