### ISSUE TITLE
Seeing Errors with Camel examples

### ISSUE THREAD

**Issue by stevef1uk** [fabric8io/fabric8-maven-plugin#599]
Taking the latest camel examples 2.18.0 from: http://www.apache.org/dyn/closer.lua?filename=camel/apache-camel/2.18.0/apache-camel-2.18.0.tar.gz&action=download

Using: minikube version: v0.10.0
java version "1.8.0_65"
16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64

Running 
mvn io.fabric8:fabric8-maven-plugin:3.1.76:setup
then
mvn fabric8:run

I am seeing:

ERROR] F8: f8-cd-doc-link: Failed to parse URL: scpexe://people.apache.org/www/camel.apache.org/maven//camel-parent/examples/camel-example-spring-boot. java.net.MalformedURLException: unknown protocol: scpexe

which can result in failures e.g. for camel-example-loan-broker:

INFO] Using namespace: default
[INFO] Creating a Deployment from kubernetes.yml namespace default name camel-example-loan-broke
[ERROR] Failed to create Deployment from kubernetes.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.99.100:8443/apis/extensions/v1beta1/namespaces/default/deployments. Message: Deployment.extensions "camel-example-loan-broke" is invalid: spec.template.spec.containers: Required value. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.template.spec.containers, message=Required value, reason=FieldValueRequired, additionalProperties={})], group=extensions, kind=Deployment, name=camel-example-loan-broke, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=Deployment.extensions "camel-example-loan-broke" is invalid: spec.template.spec.containers: Required value, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).. Deployment(apiVersion=extensions/v1beta1, kind=Deployment, metadata=ObjectMeta(annotations={fabric8.io/docs-url=scpexe://people.apache.org/www/camel.apache.org/maven//camel-parent/examples/camel-example-loan-broker, fabric8.io/iconUrl=img/icons/camel.svg, fabric8.io/metrics-path=dashboard/file/camel-routes.json/?var-project=camel-example-loan-broker&var-version=2.16.1}, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={provider=fabric8, project=camel-example-loan-broker, version=2.16.1, group=org.apache.camel}, name=camel-example-loan-broke, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=DeploymentSpec(minReadySeconds=null, paused=null, replicas=1, revisionHistoryLimit=null, rollbackTo=null, selector=LabelSelector(matchExpressions=[], matchLabels={project=camel-example-loan-broker, provider=fabric8, group=org.apache.camel}, additionalProperties={}), strategy=null, template=PodTemplateSpec(metadata=ObjectMeta(annotations={fabric8.io/iconUrl=img/icons/camel.svg, fabric8.io/metrics-path=dashboard/file/camel-routes.json/?var-project=camel-example-loan-broker&var-version=2.16.1, fabric8.io/docs-url=scpexe://people.apache.org/www/camel.apache.org/maven//camel-parent/examples/camel-example-loan-broker}, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={provider=fabric8, project=camel-example-loan-broker, version=2.16.1, group=org.apache.camel}, name=null, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, containers=[], dnsPolicy=null, host=null, hostIPC=null, hostNetwork=null, hostPID=null, hostname=null, imagePullSecrets=[], nodeName=null, nodeSelector=null, restartPolicy=null, securityContext=null, serviceAccount=null, serviceAccountName=null, subdomain=null, terminationGracePeriodSeconds=null, volumes=[], additionalProperties={}), additionalProperties={}), additionalProperties={}), status=null, additionalProperties={})
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.99.100:8443/apis/extensions/v1beta1/namespaces/default/deployments. Message: Deployment.extensions "camel-example-loan-broke" is invalid: spec.template.spec.containers: Required value. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.template.spec.containers, message=Required value, reason=FieldValueRequired, additionalProperties={})], group=extensions, kind=Deployment, name=camel-example-loan-broke, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=Deployment.extensions "camel-example-loan-broke" is invalid: spec.template.spec.containers: Required value, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:314)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:267)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:236)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:229)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:207)
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:578)
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:274)
    at io.fabric8.kubernetes.api.Controller.doCreateResource(Controller.java:900)
    at io.fabric8.kubernetes.api.Controller.applyResource(Controller.java:889)
    at io.fabric8.kubernetes.api.Controller.applyEntity(Controller.java:275)
    at io.fabric8.kubernetes.api.Controller.apply(Controller.java:224)
    at io.fabric8.maven.plugin.mojo.build.ApplyMojo.applyEntities(ApplyMojo.java:442)
    at io.fabric8.maven.plugin.mojo.develop.RunMojo.applyEntities(RunMojo.java:55)
    at io.fabric8.maven.plugin.mojo.build.ApplyMojo.executeInternal(ApplyMojo.java:394)
    at io.fabric8.maven.plugin.mojo.AbstractFabric8Mojo.execute(AbstractFabric8Mojo.java:77)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.383 s
[INFO] Finished at: 2016-10-23T15:58:02+01:00
[INFO] Final Memory: 74M/1395M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.76:run (default-cli) on project camel-example-loan-broker: Failed to create Deployment from kubernetes.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.99.100:8443/apis/extensions/v1beta1/namespaces/default/deployments. Message: Deployment.extensions "camel-example-loan-broke" is invalid: spec.template.spec.containers: Required value. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.template.spec.containers, message=Required value, reason=FieldValueRequired, additionalProperties={})], group=extensions, kind=Deployment, name=camel-example-loan-broke, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=Deployment.extensions "camel-example-loan-broke" is invalid: spec.template.spec.containers: Required value, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).. Deployment(apiVersion=extensions/v1beta1, kind=Deployment, metadata=ObjectMeta(annotations={fabric8.io/docs-url=scpexe://people.apache.org/www/camel.apache.org/maven//camel-parent/examples/camel-example-loan-broker, fabric8.io/iconUrl=img/icons/camel.svg, fabric8.io/metrics-path=dashboard/file/camel-routes.json/?var-project=camel-example-loan-broker&var-version=2.16.1}, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={provider=fabric8, project=camel-example-loan-broker, version=2.16.1, group=org.apache.camel}, name=camel-example-loan-broke, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=DeploymentSpec(minReadySeconds=null, paused=null, replicas=1, revisionHistoryLimit=null, rollbackTo=null, selector=LabelSelector(matchExpressions=[], matchLabels={project=camel-example-loan-broker, provider=fabric8, group=org.apache.camel}, additionalProperties={}), strategy=null, template=PodTemplateSpec(metadata=ObjectMeta(annotations={fabric8.io/iconUrl=img/icons/camel.svg, fabric8.io/metrics-path=dashboard/file/camel-routes.json/?var-project=camel-example-loan-broker&var-version=2.16.1, fabric8.io/docs-url=scpexe://people.apache.org/www/camel.apache.org/maven//camel-parent/examples/camel-example-loan-broker}, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={provider=fabric8, project=camel-example-loan-broker, version=2.16.1, group=org.apache.camel}, name=null, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, containers=[], dnsPolicy=null, host=null, hostIPC=null, hostNetwork=null, hostPID=null, hostname=null, imagePullSecrets=[], nodeName=null, nodeSelector=null, restartPolicy=null, securityContext=null, serviceAccount=null, serviceAccountName=null, subdomain=null, terminationGracePeriodSeconds=null, volumes=[], additionalProperties={}), additionalProperties={}), additionalProperties={}), status=null, additionalProperties={}) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by davsclaus** [comment]
Where do you run the fabric8:run command from, which directory? Can you maybe better write down the steps you do.
