### ISSUE TITLE
Failed to execute goal org.jolokia:docker-maven-plugin:0.13.6:build :Cannot create docker access object:/.docker/key.pem 

### ISSUE THREAD

**Issue by yeganx** [fabric8io/fabric8-maven-plugin#611]
_Please fill out the following information to help us in analyzing the issue, but feel free to skip it if you don't have the information at hand or if it does not apply. Please remove everything which does not apply to the issue. Including this info paragraph ;-)_
### Description

I installed openshift with vagrant file , and export all docker_env in my shell 
now in my source code , i try this command : mvn -Pf8-local-deploy on my cdi-camel-amq-archtype project 
but the out put is 
Failed to execute goal org.jolokia:docker-maven-plugin:0.13.6:build (default-cli) on project mqservice: Cannot create docker access object: /root/testopen/.vagrant/machines/default/virtualbox/.docker/key.pem (No such file or directory) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jolokia:docker-maven-plugin:0.13.6:build (default-cli) on project mqservice: Cannot create docker access object 
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Cannot create docker access object 
    at org.jolokia.docker.maven.AbstractDockerMojo.createDockerAccess(AbstractDockerMojo.java:247)
    at org.jolokia.docker.maven.AbstractDockerMojo.execute(AbstractDockerMojo.java:159)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    ... 20 more
Caused by: java.io.FileNotFoundException: /root/testopen/.vagrant/machines/default/virtualbox/.docker/key.pem (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileInputStream.<init>(FileInputStream.java:93)
    at java.io.FileReader.<init>(FileReader.java:58)
    at org.jolokia.docker.maven.access.KeyStoreUtil.loadPEM(KeyStoreUtil.java:51)
    at org.jolokia.docker.maven.access.KeyStoreUtil.loadPrivateKey(KeyStoreUtil.java:45)
    at org.jolokia.docker.maven.access.KeyStoreUtil.createDockerKeyStore(KeyStoreUtil.java:33)
    at org.jolokia.docker.maven.access.hc.http.HttpClientBuilder.getSslFactoryRegistry(HttpClientBuilder.java:76)
    at org.jolokia.docker.maven.access.hc.http.HttpClientBuilder.getConnectionFactory(HttpClientBuilder.java:67)
    at org.jolokia.docker.maven.access.hc.http.HttpClientBuilder.build(HttpClientBuilder.java:56)
    at org.jolokia.docker.maven.access.hc.DockerAccessWithHcClient.<init>(DockerAccessWithHcClient.java:85)
    at org.jolokia.docker.maven.AbstractDockerMojo.createDockerAccess(AbstractDockerMojo.java:241)
    ... 23 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
### Info
- Maven version (`mvn -v`) :
  Apache Maven 3.3.9
- java version : 
  Java version: 1.8.0_101, vendor: Oracle Corporation
- Kubernetes / OpenShift setup and version :
  oc v1.3.0
  kubernetes v1.3.0+52492b4
  features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.2.2.2:8443
kubernetes v1.2.0-36-g4a3f9c5
vagrant version : Installed Version: 1.8.5

**Comment by testphreak** [comment]
Hi @yeganx how did you end up resolving this issue? I am unable to get past this error. Using 0.20.1 (latest) of this plugin.

**Comment by irstavr** [comment]
I'm facing the same error message with ' mvn:docker build '. Any update on this? Thanks a lot.

**Comment by rohanKanojia** [comment]
@yeganx: From your logs, It looks like a docker maven plugin issue. You're using quite an old version of that too, use latest (i.e 0.27.1) and if you still face this issue; please file it on [fabric8io/docker-maven-plugin](https://github.com/fabric8io/docker-maven-plugin).
