### ISSUE TITLE
Lack of metadata.name value in kubernetes.yml

### ISSUE THREAD

**Issue by muraken720** [fabric8io/fabric8-maven-plugin#618]
### Description

My project name is "spring-cloud-kubernetes-example".
When I do "mvn fabric8:run", below error is occured.
In target/classes/META-INF/fabric8/kubernetes.yml, metadata.name is "spring-cloud-kubernetes-".
My expectation is "metadata.name = spring-cloud-kubernetes-example".
### Info
- f-m-p version :3.1.81 and 3.1.83
- Maven version (`mvn -v`) :3.3.9

```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T01:41:47+09:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_111, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre
Default locale: ja_JP, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```
- console error log

```
[INFO] --- fabric8-maven-plugin:3.1.83:run (default-cli) @ spring-cloud-kubernetes-example ---
[INFO] F8: Using Kubernetes at https://192.168.64.8:8443/ in namespace default with manifest /Users/ken/work/spring-cloud-kubernetes-example/target/classes/META-INF/fabric8/kubernetes.yml 
[INFO] Using namespace: default
[INFO] Creating a Service from kubernetes.yml namespace default name spring-cloud-kubernetes-
[ERROR] Failed to create Service from kubernetes.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.64.8:8443/api/v1/namespaces/default/services. Message: Service "spring-cloud-kubernetes-" is invalid: metadata.name: Invalid value: "spring-cloud-kubernetes-": must match the regex [a-z]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or 'abc-123'). Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.name, message=Invalid value: "spring-cloud-kubernetes-": must match the regex [a-z]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or 'abc-123'), reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Service, name=spring-cloud-kubernetes-, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=Service "spring-cloud-kubernetes-" is invalid: metadata.name: Invalid value: "spring-cloud-kubernetes-": must match the regex [a-z]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or 'abc-123'), metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).. Service(apiVersion=v1, kind=Service, metadata=ObjectMeta(annotations={prometheus.io/port=9779, prometheus.io/scrape=true, fabric8.io/git-commit=55cf8dc83e60192b667adb20c5dc13809f7d7573, fabric8.io/iconUrl=img/icons/spring-boot.svg, fabric8.io/git-branch=master}, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={expose=true, provider=fabric8, project=spring-cloud-kubernetes-example, version=0.0.1-SNAPSHOT, group=com.example}, name=spring-cloud-kubernetes-, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=ServiceSpec(clusterIP=null, deprecatedPublicIPs=[], externalIPs=[], loadBalancerIP=null, loadBalancerSourceRanges=[], portalIP=null, ports=[ServicePort(name=http, nodePort=null, port=80, protocol=TCP, targetPort=IntOrString(IntVal=8080, Kind=null, StrVal=null, additionalProperties={}), additionalProperties={})], selector={project=spring-cloud-kubernetes-example, provider=fabric8, group=com.example}, sessionAffinity=null, type=LoadBalancer, additionalProperties={}), status=null, additionalProperties={})
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.64.8:8443/api/v1/namespaces/default/services. Message: Service "spring-cloud-kubernetes-" is invalid: metadata.name: Invalid value: "spring-cloud-kubernetes-": must match the regex [a-z]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or 'abc-123'). Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.name, message=Invalid value: "spring-cloud-kubernetes-": must match the regex [a-z]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or 'abc-123'), reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Service, name=spring-cloud-kubernetes-, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=Service "spring-cloud-kubernetes-" is invalid: metadata.name: Invalid value: "spring-cloud-kubernetes-": must match the regex [a-z]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or 'abc-123'), metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:315)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:268)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:208)
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:602)
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:274)
    at io.fabric8.kubernetes.api.Controller.doCreateService(Controller.java:1081)
    at io.fabric8.kubernetes.api.Controller.applyService(Controller.java:1018)
    at io.fabric8.maven.plugin.mojo.build.ApplyMojo.applyEntities(ApplyMojo.java:437)
    at io.fabric8.maven.plugin.mojo.develop.RunMojo.applyEntities(RunMojo.java:55)
    at io.fabric8.maven.plugin.mojo.build.ApplyMojo.executeInternal(ApplyMojo.java:394)
    at io.fabric8.maven.plugin.mojo.AbstractFabric8Mojo.execute(AbstractFabric8Mojo.java:77)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.596 s
[INFO] Finished at: 2016-10-29T22:25:46+09:00
[INFO] Final Memory: 53M/506M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.83:run (default-cli) on project spring-cloud-kubernetes-example: Failed to create Service from kubernetes.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.64.8:8443/api/v1/namespaces/default/services. Message: Service "spring-cloud-kubernetes-" is invalid: metadata.name: Invalid value: "spring-cloud-kubernetes-": must match the regex [a-z]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or 'abc-123'). Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.name, message=Invalid value: "spring-cloud-kubernetes-": must match the regex [a-z]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or 'abc-123'), reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Service, name=spring-cloud-kubernetes-, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=Service "spring-cloud-kubernetes-" is invalid: metadata.name: Invalid value: "spring-cloud-kubernetes-": must match the regex [a-z]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or 'abc-123'), metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).. Service(apiVersion=v1, kind=Service, metadata=ObjectMeta(annotations={prometheus.io/port=9779, prometheus.io/scrape=true, fabric8.io/git-commit=55cf8dc83e60192b667adb20c5dc13809f7d7573, fabric8.io/iconUrl=img/icons/spring-boot.svg, fabric8.io/git-branch=master}, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={expose=true, provider=fabric8, project=spring-cloud-kubernetes-example, version=0.0.1-SNAPSHOT, group=com.example}, name=spring-cloud-kubernetes-, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=ServiceSpec(clusterIP=null, deprecatedPublicIPs=[], externalIPs=[], loadBalancerIP=null, loadBalancerSourceRanges=[], portalIP=null, ports=[ServicePort(name=http, nodePort=null, port=80, protocol=TCP, targetPort=IntOrString(IntVal=8080, Kind=null, StrVal=null, additionalProperties={}), additionalProperties={})], selector={project=spring-cloud-kubernetes-example, provider=fabric8, group=com.example}, sessionAffinity=null, type=LoadBalancer, additionalProperties={}), status=null, additionalProperties={}) -> [Help 1]
```
- kubernetes-yml

```
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
      fabric8.io/git-commit: "55cf8dc83e60192b667adb20c5dc13809f7d7573"
      fabric8.io/iconUrl: "img/icons/spring-boot.svg"
      fabric8.io/git-branch: "master"
    labels:
      expose: "true"
      provider: "fabric8"
      project: "spring-cloud-kubernetes-example"
      version: "0.0.1-SNAPSHOT"
      group: "com.example"
    name: "spring-cloud-kubernetes-"

...

  - apiVersion: "extensions/v1beta1"
  kind: "Deployment"
  metadata:
    annotations:
      fabric8.io/git-commit: "55cf8dc83e60192b667adb20c5dc13809f7d7573"
      fabric8.io/iconUrl: "img/icons/spring-boot.svg"
      fabric8.io/git-branch: "master"
      fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=spring-cloud-kubernetes-example&var-version=0.0.1-SNAPSHOT"
    labels:
      provider: "fabric8"
      project: "spring-cloud-kubernetes-example"
      version: "0.0.1-SNAPSHOT"
      group: "com.example"
    name: "spring-cloud-kubernetes-"
```
- Kubernetes / OpenShift setup and version :minikube version: v0.12.0
- If it's a bug, how to reproduce : clone my project and mvn fabric8:run
- Sample project : https://github.com/muraken720/spring-cloud-kubernetes-example

**Comment by muraken720** [comment]
I tried to recreate new project, https://github.com/muraken720/spring-cloud-k8s-example
In this new project, it dose not occur.
So I'm going to close this issue.
