### ISSUE TITLE
fabric8-maven-plugin:3.1.86:build failed: A JSONObject text must begin with '{'

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8-maven-plugin#634]
### Description
Building a new 'Microservice' project using the fabric8 console wizard on minikube, the first build has failed with this error:

```
fabric8-maven-plugin:3.1.86:build failed: A JSONObject text must begin with '{'
```

Full jenkins job log can be found: https://gist.github.com/rawlingsj/cfd86ccfdfb8f6bff1603985cc760ea9

### Info

* f-m-p version : 3.1.86

To recreate:
```
git clone https://github.com/fabric8io/fabric8-platform
cd fabric8-platform
mvn clean install
gofabric8 start --package=packages/fabric8-platform/target/classes/META-INF/fabric8/kubernetes.yml
```
Then create a new project selecting the Microservices new project wizard.
Select a pipeline, I chose release / stage / approve / promote

Pipeline is started and fails with error above

**Comment by rawlingsj** [comment]
I've cloned the project locally and I can't reproduce the error outside of the pipeline.  Still investigating...

**Comment by rhuss** [comment]
Could you please run it with the maven option -e in the pipeline build ?

James Rawlings <notifications@github.com> schrieb am Do., 3. Nov. 2016,
12:21:

**Comment by rawlingsj** [comment]
sure thing, this looks helpful:

```
[INFO] <<< fabric8-maven-plugin:3.1.86:build (default) < package @ micro <<<
160 	[INFO] 
161 	[INFO] --- fabric8-maven-plugin:3.1.86:build (default) @ micro ---
162 	[INFO] F8: Building Docker image in Kubernetes mode
163 	[INFO] F8: spring-boot: Using fat jar packaging as the spring boot plugin is using `repackage` goal execution
164 	[INFO] F8: Running generator spring-boot
165 	[INFO] ------------------------------------------------------------------------
166 	[INFO] BUILD FAILURE
167 	[INFO] ------------------------------------------------------------------------
168 	[INFO] Total time: 14.618 s
169 	[INFO] Finished at: 2016-11-03T13:01:13+00:00
170 	sh-4.2# exit
171 	exit
172 	[INFO] Final Memory: 55M/382M
173 	[INFO] ------------------------------------------------------------------------
174 	[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.86:build (default) on project micro: Execution default of goal io.fabric8:fabric8-maven-plugin:3.1.86:build failed: A JSONObject text must begin with '{' at 1 [character 2 line 1] -> [Help 1]
175 	org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.86:build (default) on project micro: Execution default of goal io.fabric8:fabric8-maven-plugin:3.1.86:build failed: A JSONObject text must begin with '{' at 1 [character 2 line 1]
176 		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
177 		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
178 		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
179 		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
180 		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
181 		at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
182 		at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
183 		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
184 		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
185 		at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
186 		at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
187 		at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
188 		at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
189 		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
190 		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
191 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
192 		at java.lang.reflect.Method.invoke(Method.java:498)
193 		at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
194 		at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
195 		at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
196 		at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
197 	Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal io.fabric8:fabric8-maven-plugin:3.1.86:build failed: A JSONObject text must begin with '{' at 1 [character 2 line 1]
198 		at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
199 		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
200 		... 20 more
201 	Caused by: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
202 		at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
203 		at org.json.JSONObject.<init>(JSONObject.java:194)
204 		at io.fabric8.maven.docker.util.AuthConfigFactory.readDockerConfig(AuthConfigFactory.java:303)
205 		at io.fabric8.maven.docker.util.AuthConfigFactory.getAuthConfigFromDockerConfig(AuthConfigFactory.java:223)
206 		at io.fabric8.maven.docker.util.AuthConfigFactory.createAuthConfig(AuthConfigFactory.java:125)
207 		at io.fabric8.maven.docker.AbstractDockerMojo.prepareAuthConfig(AbstractDockerMojo.java:393)
208 		at io.fabric8.maven.docker.AbstractDockerMojo.checkImageWithAutoPull(AbstractDockerMojo.java:438)
209 		at io.fabric8.maven.docker.AbstractBuildSupportMojo.autoPullBaseImage(AbstractBuildSupportMojo.java:110)
210 		at io.fabric8.maven.docker.AbstractBuildSupportMojo.buildImage(AbstractBuildSupportMojo.java:63)
211 		at io.fabric8.maven.docker.BuildMojoNoFork.buildAndTag(BuildMojoNoFork.java:55)
212 		at io.fabric8.maven.plugin.mojo.build.BuildMojo.buildAndTag(BuildMojo.java:270)
213 		at io.fabric8.maven.docker.BuildMojoNoFork.executeInternal(BuildMojoNoFork.java:46)
214 		at io.fabric8.maven.plugin.mojo.build.BuildMojo.executeInternal(BuildMojo.java:253)
215 		at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:193)
216 		at io.fabric8.maven.plugin.mojo.build.BuildMojo.execute(BuildMojo.java:236)
217 		at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
218 		... 21 more
219 	[ERROR] 
```

**Comment by rhuss** [comment]
It looks like that your "~/.docker/config.json" is broknen and not valid
JSON. At chance that you can get hold of it ?

**Comment by rawlingsj** [comment]
yeah - the file exists but is empty, it's a secret that gets mounted.  

What's odd though is this happening intermittently. I triggered a new build in jenkins and it worked and the build pod still has a empty config.json.

**Comment by rhuss** [comment]
just kicked off a 0.17.2 build (luckily had some wifi right now ;-)

**Comment by rhuss** [comment]
of d-m-p I mean.

**Comment by rawlingsj** [comment]
ok cool - I can update the d-m-p version in this repo once the d-m-p release is done and PR for you to merge if you like?
