### ISSUE TITLE
No such generated manifest when running `mvn fabric8:build -Popenshift`

### ISSUE THREAD

**Issue by iocanel** [fabric8io/fabric8-maven-plugin#768]
In a new project I am running:

    mvn fabric8:build -Popenshift 

which fails with:

    [ERROR] F8: No such generated manifest file: /tmp/quick_rest_springboot-tomcat/target/classes/META-INF/fabric8/openshift.yml

### Description

Noticed this glitch while I was looking at: https://issues.jboss.org/browse/OSFUSE-483

This goes away if I add `fabric8:resource` into the mix. 

### Info

* f-m-p version :  fabric8-maven-plugin:3.1.80.redhat-000004
* Maven version (`mvn -v`) : 3.3.9

**Comment by iocanel** [comment]
@rhuss: Do we need to explictly specify fabric8:resource?

Can we automatically generate the resources, if we need them and they are not available or explicitly generated?

**Comment by rhuss** [comment]
@iocanel could you please paste the stacktrace coming from `mvn -e` ? 

Normally a `fabric8:build` should not require a `fabric8:resource`, however it still makes much sense to call this before `fabric8:build` as the generated descriptors are also included in the artifact (jar) which are then part of the image (so it as much required a 'resources' is required for a 'compile' goal). Therefore when we bind both `fabric8:resource` and `fabric8:build`  both to executions so that they typically always called in the right order/combination when using standard maven phases/goals.

**Comment by iocanel** [comment]
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.80.redhat-000004:build (default-cli) on project springboot-rest: No such generated manifest file: /tmp/quick_rest_springboot-tomcat/target/classes/META-INF/fabric8/openshift.yml -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.80.redhat-000004:build (default-cli) on project springboot-rest: No such generated manifest file: /tmp/quick_rest_springboot-tomcat/target/classes/META-INF/fabric8/openshift.yml
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: No such generated manifest file: /tmp/quick_rest_springboot-tomcat/target/classes/META-INF/fabric8/openshift.yml
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.generateImageStreamTags(BuildMojo.java:429)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.executeOpenShiftBuild(BuildMojo.java:341)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.buildAndTag(BuildMojo.java:272)
	at io.fabric8.maven.docker.BuildMojo.executeInternal(BuildMojo.java:47)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.executeInternal(BuildMojo.java:253)
	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:193)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.execute(BuildMojo.java:236)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.maven.plugin.MojoFailureException: No such generated manifest file: /tmp/quick_rest_springboot-tomcat/target/classes/META-INF/fabric8/openshift.yml
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.generateImageStreamTags(BuildMojo.java:398)
	... 28 more

**Comment by iocanel** [comment]
@rhuss: fwiw there are both resource and build defined in the excecutions.

**Comment by rhuss** [comment]
@iocanel ok, but you called 'mvn fabric8:build', not 'mvn install' (in which case fabric8:resource would have been called, too).

I suggesst to clarify the error message since I hesitate to implicitly call other goals (which btw is even not so easy from Maven). I'm still not sure why this is needed here, it looks like its about adding certain `ImageStreamTags` to the created image of an s2i binary build, but I thought this is already done by OpenShift. @jstrachan do you know why we need to create extra ImageStreamTags [here](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java#L358)

This is the only code which couples `fabric8:build` to `fabric8:resource` and I indeed would love to keep them decoupled. Maybe we can serve the use case (which I dont know or remember) in a different way ?

**Comment by iocanel** [comment]
Sure, but if fabric8:build requires the the presence of the resources, shouldn't we create them, if they are not there?

**Comment by rhuss** [comment]
No, normally fabric8:build does not requires the resources. You need the resources only for deployment.

Ok, they resources _should_ be added to the jar for references, but this is not mandatory for running it.

Why I'm so picky about calling out to fabric8:resources ? The reason is that there are so many subtle dependencies when calling goals. We already had a lot of issues when goals be called twiced (because the forked the lifecycle and the like). What e.g. should be done when 'fabric8:build' does not an OpenShift but an Kubernetes build ? Which means a plain Docker build against a Docker daemon which for sure does not need any resource descriptors ? Creating the resources in this case would be overkill. 

Also since fabric8:build happens after the package phase where the Jar file is created, creating resources at that point in time with fabric8:build is already too late to include them into the jar. Which again makes up for inconsistent behaviour.

We should not do much magic implicitely which makes it hard to track the flow through the various phases of the plugin (which should stay at the responsibility of Maven). A good error message like "Please call fabric8:resource before calling fabric8:build" is imo the better solution.

However, the only reason  for calling fabric8:resource is the creation of ImageStreams from the resource descriptors during the build phase where I don't grok the use case. If this (unknown) use case can be solved differently all would be good. @jstrachan can you enlight me ?

**Comment by iocanel** [comment]
Since fabric8:build doesn't normally require the resources, then I think it should be fine if we just added a message.

**Comment by rhuss** [comment]
@jstrachan : Is [this check](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java#L460-L465) correct ? I suspect it to be the other way round (`if (spec == null)`) otherwise one would get an NPE if `spec == null` (or spec is always != null, then the `if` is superfluous).

Currently I'm trying to follow the code in BuildMojo, which updates the `openshift.yml` based on the ImageStreams available on the current OpenShift installation. Although I'm not yet through it, I really don't get yet why we need to update `openshift.yml` with specific information from the currently running OpenShift cluster where the build happens. This `openshift.yml` is included in jar files and are released to Maven where it can be reused for aggregation. So imo there should be *never* any installation specific data included here. If this ever would be necessary, then a different file should be used which is only temporary and not part of the Maven artefact. However, I wonder why we should include ImageStreams at all in the resource descriptors which we generate.

Another point which is find suboptimal is the call to static methods in ApplyMojo and ResourceMojo from BuildMojo which tightly couples entities which are supposed to be decoupled and to be called independently. If there is shared code it should for sure be extracted in extra classes if absolutely necessary. But then I still think that the `BuildMojo` is responsible for building images or imagestreams, not for creating or appending to deployment descriptors (ResourceMojo), neither for applying these to the cluster (ApplyMojo).

This is not an academic question as this issue proves.

**Comment by rhuss** [comment]
I think I found a good solution so that the generation of the image stream objects from a running cluster are written in an extra file (and not into `openshift.yml` anymore). Anyone who is required to use this file can pick it up from there (still dont know the use case, though). 

It shouldn't be a problem that this imagestream is not in openshift.yml anyway, as the openshift.yml included in the jar doesn't contain it as it has been build and put into the artifact jar much before `fabric8:build` as run anyway. So it was available locally in the `target` dir only anyway. As it is now, just in another file.

By default the creation of this extra file is disabled. It's debatable whether to enable it by default, but only when I get an idea of the use case ;-)
