### ISSUE TITLE
fabric8:import gives a read timeout

### ISSUE THREAD

**Issue by h4ckroot** [fabric8io/fabric8-maven-plugin#795]
### Description
I have a kubernetes cluster which is hosted on the cloud. The version for kubernetes is 1.4.8. I configured my local kubectl to refere to the remote cluster, and I can see the nodes when I fire kubectl get nodes. The issue is, i am trying to import a spring boot application using fabric8:import, but I got a read time out. The full stack trace:

<details>
<summary><strong>Stacktrace</strong></summary>
```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.2.14:import (default-cli) on project distributed-tracking-web: An error has occurred. timeout: Socket closed -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.2.14:import (default-cli) on project distributed-tracking-web: An error has occurred.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An error has occurred.
	at io.fabric8.maven.core.util.KubernetesResourceUtil.handleKubernetesClientException(KubernetesResourceUtil.java:430)
	at io.fabric8.maven.plugin.mojo.internal.ImportMojo.executeInternal(ImportMojo.java:209)
	at io.fabric8.maven.plugin.mojo.AbstractFabric8Mojo.execute(AbstractFabric8Mojo.java:74)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:57)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:508)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:62)
	at io.fabric8.maven.plugin.mojo.internal.ImportMojo.findBuildConfigForGitRepo(ImportMojo.java:499)
	at io.fabric8.maven.plugin.mojo.internal.ImportMojo.executeInternal(ImportMojo.java:165)
	... 23 more
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:210)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:288)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:242)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:53)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at io.fabric8.kubernetes.api.KubernetesHelper$JenkinShiftClient$2.intercept(KubernetesHelper.java:2351)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.execute(RealCall.java:60)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:235)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:506)
	... 26 more
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:203)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
	... 52 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
shami@h4ckr007 distributed-tracking-web $ 
shami@h4ckr007 distributed-tracking-web $ mvn fabric8:deploy
```
</details>

* f-m-p version : version 3.2.14
* Maven version (`mvn -v`) : version 3.3.9
* Kubernetes / OpenShift setup and version :
Kubernetes cloud cluster of one master and two nodes.

**Comment by rhuss** [comment]
It looks like that although Kubernetes is used, the `fabric8:import` tries to read `BuildConfig` [here](https://github.com/rhuss/fabric8-maven-plugin/blob/9b6e11e2693217ed8b8c6270a2409ddd22ac8633/plugin/src/main/java/io/fabric8/maven/plugin/mojo/internal/ImportMojo.java#L499-L499) which obviously doesn't work.

@jstrachan : Is `fabric8:import` supposed to work for Kubernetes, too ? A naive look into the code suggest that if a `gitRemoteUrl` is provided, then OpenShift is assumed, otherwise Kubernetes (??)

@iocanel : I wonder why the read fails with a timeout. Of course it has to fail, because it is tried to read an OpenShift object form a Kubernetes API-Server but I would expect to fail faster and with a more clear error message ?  (see stack trace above)

**Comment by h4ckroot** [comment]
any update please ??

**Comment by thangs1** [comment]
Hi, I too see this issue in my local setup. Did we find a solution yet?

**Comment by rohanKanojia** [comment]
fabric8:import got removed in #1313, so closing this
