### ISSUE TITLE
Spring Boot Port Extractor - NumberFormat Exception

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/fabric8-maven-plugin#880]
### Description
The Spring Boot port extractor fails to handle server.port with value like `sever.port: ${PORT:10800}` , throws NumberFormatException

### Info

* f-m-p version : 3.2.30
* Maven version (`mvn -v`) : 3.3.9
* OpenShift setup and version : 3.4.0
* If it's a bug, how to reproduce :
  * Create a simple simple spring boot project 
  * add a resource called `application.yml` with value of `server.port` to be equal to `${PORT:1234}`
 * run`mvn clean package`

### Stack Trace:

```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.2.30:resource (default) on project config-server: Execution default of goal io.fabric8:fabric8-maven-plugin:3.2.30:resource failed: Cannot extract generator: java.lang.NumberFormatException: For input string: "${PORT:8888}" -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.2.30:resource (default) on project config-server: Execution default of goal io.fabric8:fabric8-maven-plugin:3.2.30:resource failed: Cannot extract generator: java.lang.NumberFormatException: For input string: "${PORT:8888}"
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:181)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal io.fabric8:fabric8-maven-plugin:3.2.30:resource failed: Cannot extract generator: java.lang.NumberFormatException: For input string: "${PORT:8888}"
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 11 more
Caused by: java.lang.IllegalArgumentException: Cannot extract generator: java.lang.NumberFormatException: For input string: "${PORT:8888}"
	at io.fabric8.maven.plugin.mojo.build.ResourceMojo$4.customizeConfig(ResourceMojo.java:613)
	at io.fabric8.maven.docker.config.ConfigHelper.resolveImages(ConfigHelper.java:51)
	at io.fabric8.maven.plugin.mojo.build.ResourceMojo.getResolvedImages(ResourceMojo.java:586)
	at io.fabric8.maven.plugin.mojo.build.ResourceMojo.executeInternal(ResourceMojo.java:197)
	at io.fabric8.maven.plugin.mojo.AbstractFabric8Mojo.execute(AbstractFabric8Mojo.java:74)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 12 more
Caused by: java.lang.NumberFormatException: For input string: "${PORT:8888}"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.parseInt(Integer.java:615)
	at io.fabric8.maven.generator.javaexec.JavaExecGenerator.addPortIfValid(JavaExecGenerator.java:244)
	at io.fabric8.maven.generator.springboot.SpringBootGenerator.extractPorts(SpringBootGenerator.java:103)
	at io.fabric8.maven.generator.javaexec.JavaExecGenerator.customize(JavaExecGenerator.java:115)
	at io.fabric8.maven.generator.springboot.SpringBootGenerator.customize(SpringBootGenerator.java:78)
	at io.fabric8.maven.plugin.generator.GeneratorManager.generate(GeneratorManager.java:62)
	at io.fabric8.maven.plugin.mojo.build.ResourceMojo$4.customizeConfig(ResourceMojo.java:611)
	... 17 more
```

**Comment by kameshsampath** [comment]
@rhuss   - got an idea to solve this, how good it would be to allow us to add a property called `spring-boot.profile` and load the `application-${spring-boot.profile}` during build ?

**Comment by rhuss** [comment]
The ports are supposed to be integer values. If used with Maven properties these property should contain a numeric value. Since Maven doesn't support default values with this syntax, it takes over the expression literally which obviously can not be parsed as a number.

So its not a bug, maybe a missing feature. But let's discuss whether the plugin (or only the generator ? ) should support an own expression language for properties (which might collide with Maven's property resolution). Currently I don't think this should be the case, but I'm open for arguments of course ;-)

**Comment by rhuss** [comment]
@kameshsampath you mean for examing the values what to expose ?

Then I'd suggest to a a config option `profile` (which would translate to a property generator.spring-boot.profile`) and adapt the lookup mechanism according to the way how spring-boot would do the lookup (e.g. still, a `application.properties` should be looked up for default values).

Then we could also automatically adapt the JAVA_OPTIONS to include the profile to be selected during runtime.

Is this something which would cover your use case ?

**Comment by kameshsampath** [comment]
yes @rhuss - yes thats exactly what I prefer as well. so we can achieve two things with same config property called `profile`, once its set we use that in our SpringBootUtil to load the respective properties and  then add to JAVA_OPTIONS value of `-Dspring.profiles.active=config.profile`

**Comment by rhuss** [comment]
Sounds good ;-)

btw, I wonder if we at some point should even examine more places for finding configuration values as it is described in https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

For adding the extra option, simply add to `SpringBootGenerator.getExtraJavaOptions()`.

**Comment by kameshsampath** [comment]
@rhuss please check/review PR #881 - thats handle Issue #797 and implementation inline with this issue as well.
