### ISSUE TITLE
OC Cluster Up command support

### ISSUE THREAD

**Issue by RobWin** [fabric8io/fabric8-maven-plugin#922]
Hello,

I would like to use the `oc cluster up` command to start a local OpenShift all-in-one cluster.
I tried to use the plugin and configured the local registry, but I still can't build and push the project.

Unfortunately I don't understand the error message

```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.3.5:build (default-cli) on project messaging-proxy: Failed to execute the build: Unable to build the image using the OpenShift build service: Failure executing: POST at: https://192.168.3.60:8443/oapi/v1/namespaces/default/buildconfigs/messaging-proxy-s2i/instantiatebinary?commit=. Message: build messaging-proxy-s2i-11 failed: : . Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=build messaging-proxy-s2i-11 failed: : , metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}). -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.3.5:build (default-cli) on project messaging-proxy: Failed to execute the build
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to execute the build
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.buildAndTag(BuildMojo.java:233)
	at io.fabric8.maven.docker.BuildMojo.executeInternal(BuildMojo.java:44)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.executeInternal(BuildMojo.java:210)
	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:223)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.execute(BuildMojo.java:189)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: io.fabric8.maven.core.service.Fabric8ServiceException: Unable to build the image using the OpenShift build service
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildService.build(OpenshiftBuildService.java:90)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.buildAndTag(BuildMojo.java:230)
	... 26 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.3.60:8443/oapi/v1/namespaces/default/buildconfigs/messaging-proxy-s2i/instantiatebinary?commit=. Message: build messaging-proxy-s2i-11 failed: : . Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=build messaging-proxy-s2i-11 failed: : , metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:332)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:271)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:241)
	at io.fabric8.openshift.client.dsl.internal.BuildConfigOperationsImpl.fromInputStream(BuildConfigOperationsImpl.java:271)
	at io.fabric8.openshift.client.dsl.internal.BuildConfigOperationsImpl.fromFile(BuildConfigOperationsImpl.java:228)
	at io.fabric8.openshift.client.dsl.internal.BuildConfigOperationsImpl.fromFile(BuildConfigOperationsImpl.java:66)
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildService.startBuild(OpenshiftBuildService.java:247)
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildService.build(OpenshiftBuildService.java:82)
	... 27 more
```

Do I have to configure other settings? Please see my [POM.xml](https://github.com/RobWin/messaging-proxy/blob/master/pom.xml#L199)
Does this plugin support another OpenShift cluster which is not started with Minishift?

### Info

* f-m-p version : 3.3.5
* Maven version (`mvn -v`) : 3.3.9
*  oc v1.5.0+031cbe4
* kubernetes v1.5.2+43a9be4

**Comment by rhuss** [comment]
Can you reach you OpenShift cluster with e.g. `oc get nodes`  ? It look like a connection problem to the openshift server.

**Comment by RobWin** [comment]
Yes, the OC client works.
```
oc get builds   
NAME                     TYPE      FROM      STATUS    STARTED   DURATION
messaging-proxy-s2i-10   Source    Binary    Failed              
messaging-proxy-s2i-11   Source    Binary    Failed        
```
I investigate why the builds have failed.

**Comment by RobWin** [comment]
But if should work in general, I can close the issue and investigate further.

**Comment by rhuss** [comment]
Yes, it should work. We use f-m-p very often with minishift which internally uses `oc cluster up`, too. This shouldn't be a general problem.

You can leave this issue open if you need some further assistance (even when its not a bug ;-)

**Comment by RobWin** [comment]
I guess I have the same issue like this issue: https://github.com/openshift/origin/issues/13915 or this issue: https://github.com/openshift/origin/issues/13937

**Comment by rhuss** [comment]
yes, I've seen that. It's a regression coming in probably with origin 1.5.0 so if you have the chance to use still an older version you could retry (minishift comes with an option to the select the origin version)

**Comment by RobWin** [comment]
I could be my Docker version: https://github.com/openshift/origin/issues/13284

**Comment by RobWin** [comment]
It works after downgrading from Docker v17.04.0-ce to Docker 1.13.1

**Comment by RobWin** [comment]
Spam spam :) Btw the plugin is awesome work. Thanks :+1:

**Comment by rohanKanojia** [comment]
It doesn't look like a bug to me, so closing this. Feel free to reopen if anyone still faces this.
