### ISSUE TITLE
Issues with spring-boot and `fabric:watch`

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#928]
Issue found during demo preparation in spring-boots watch feature;

* `fabric8:watch` only works when `fabric8:build` is bound to execution. This should be either documented or the restriction relaxed.
* When application is already running, `fabric8:watch` doesnt stop the application or scale it to 0. This results in letting the old pod (without devtools) still running instead of spinning up a new pod with the new image. Temporary workaround: Always call `mvn fabric8:undeploy fabric8:watch`
* `fabric8:watch` doesn't work reliably (or at all ?) with multiple replicas. Only some get updated, for other there occur several different kind of exception like

```
F8: spring-boot: 2017-05-08 17:45:41.787  INFO 1 --- [           main] jax2017.RandomGeneratorApplication       : Started RandomGeneratorApplication in 4.2 seconds (JVM running for 5.675)
[ERROR] Invalid event type
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:601)
	at java.lang.Long.parseLong(Long.java:631)
	at java.text.DigitList.getLong(DigitList.java:195)
	at java.text.DecimalFormat.parse(DecimalFormat.java:2051)
	at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:2162)
	at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1514)
	at java.text.DateFormat.parse(DateFormat.java:364)
	at io.fabric8.kubernetes.api.KubernetesHelper.parseDate(KubernetesHelper.java:1908)
	at io.fabric8.maven.core.util.KubernetesResourceUtil.parseTimestamp(KubernetesResourceUtil.java:577)
	at io.fabric8.maven.core.util.KubernetesResourceUtil.getCreationTimestamp(KubernetesResourceUtil.java:568)
	at io.fabric8.maven.core.util.KubernetesResourceUtil.isNewerResource(KubernetesResourceUtil.java:619)
	at io.fabric8.maven.core.service.PortForwardService.getNewestPod(PortForwardService.java:222)
	at io.fabric8.maven.core.service.PortForwardService.access$200(PortForwardService.java:52)
	at io.fabric8.maven.core.service.PortForwardService$2.eventReceived(PortForwardService.java:150)
	at io.fabric8.maven.core.service.PortForwardService$2.eventReceived(PortForwardService.java:136)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:217)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:307)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

or 

```
let        : FrameworkServlet 'dispatcherServlet': initialization completed in 38 ms
[ERROR] Invalid event type
[ERROR] Invalid event type
java.lang.NumberFormatException: multiple points
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1890)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.text.DigitList.getDouble(DigitList.java:169)
	at java.text.DecimalFormat.parse(DecimalFormat.java:2056)
	at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:1869)
	at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1514)
	at java.text.DateFormat.parse(DateFormat.java:364)
	at io.fabric8.kubernetes.api.KubernetesHelper.parseDate(KubernetesHelper.java:1908)
	at io.fabric8.maven.core.util.KubernetesResourceUtil.parseTimestamp(KubernetesResourceUtil.java:577)
	at io.fabric8.maven.core.util.KubernetesResourceUtil.getCreationTimestamp(KubernetesResourceUtil.java:568)
	at io.fabric8.maven.core.util.KubernetesResourceUtil.isNewerResource(KubernetesResourceUtil.java:619)
	at io.fabric8.maven.core.service.PortForwardService.getNewestPod(PortForwardService.java:222)
	at io.fabric8.maven.core.service.PortForwardService.access$200(PortForwardService.java:52)
	at io.fabric8.maven.core.service.PortForwardService$2.eventReceived(PortForwardService.java:150)
	at io.fabric8.maven.core.service.PortForwardService$2.eventReceived(PortForwardService.java:136)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:217)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:307)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NumberFormatException: multiple points
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1890)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
```

**Comment by rhuss** [comment]
@nicolaferraro these are the issues I hit. BTW, when using the combination `mvn fabric8:undeploy fabric8:watch` and using only a single replica (which imo makes much sense when developing), it worked reliably all the time. Even (sometimes ;-) with LiveReload enabled. And is was also quite fast.

**Comment by nicolaferraro** [comment]
Happy to hear that :)

There is a high number of participants and many possible starting points, so I'll try to fix these issues to improve it!

**Comment by rhuss** [comment]
yeah, thanks a lot @nicolaferraro. Awesome work ! People loved it and it was one the highlight of my talk (which went quite well).

**Comment by rhuss** [comment]
I think we could maybe simple force to scale down to one pod for `fabric8:watch` ? (as we already modified quite a bit the image so this doesn't add much). Makes it easier for `fabric8:debug`, too.

**Comment by nicolaferraro** [comment]
@rhuss I can't replicate the issue about the old pod that is not scaled to 0. The watch mojo updates the deployment, so it should take care of performing the rolling update. The watch creates as many replicas as they are declared in the fragment (e.g. `deployment.yml` with `spec -> replicas = 3`), or 1 if no fragment is present.

**Comment by rhuss** [comment]
Ok, let me check this later again. Could be that it only was this date parser issue.
