### ISSUE TITLE
fabric8:import fails immediately

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#950]
With version 3.3.5 and 3.4.0 a `mvn fabric8:imports` fails immediately with 

```
mvn fabric8:import -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building random-generator 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- fabric8-maven-plugin:3.3.5:import (default-cli) @ random-generator ---
[INFO] F8: Running 1 endpoints of gogs in namespace default
Please enter your username for git repo gogs: gogsadmin
Please enter your password/access token for git repo gogs: RedHat$1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.168 s
[INFO] Finished at: 2017-05-24T08:38:39+02:00
[INFO] Final Memory: 32M/334M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.3.5:import (default-cli) on project random-generator: 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.3.5:import (default-cli) on project random-generator: 1
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: 1
	at io.fabric8.maven.plugin.mojo.internal.ImportMojo.executeInternal(ImportMojo.java:211)
	at io.fabric8.maven.plugin.mojo.AbstractFabric8Mojo.execute(AbstractFabric8Mojo.java:74)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at io.fabric8.project.support.IniFileUtils.parseIniFile(IniFileUtils.java:73)
	at io.fabric8.project.support.GitUtils.parseGitConfig(GitUtils.java:312)
	at io.fabric8.maven.plugin.mojo.internal.ImportMojo.findEmailFromDotGitConfig(ImportMojo.java:444)
	at io.fabric8.maven.plugin.mojo.internal.ImportMojo.createGogsUserDetails(ImportMojo.java:382)
	at io.fabric8.maven.plugin.mojo.internal.ImportMojo.executeInternal(ImportMojo.java:183)
	... 23 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Note that this is a project which is **not** versioned in git.

@jstrachan Is it supposed that for `mvn fabric8:import` to work that there must be a local git repo (as it is seems from the error message) ?

**Comment by rhuss** [comment]
It fails the same way even after a `git init .`

**Comment by rhuss** [comment]
Reasion is https://github.com/fabric8io/fabric8/issues/6865

**Comment by rhuss** [comment]
See https://github.com/fabric8io/fabric8-maven-plugin/pull/949/commits/fbae2d884ccba48fb93db7677174d9908408b552 for a fix.

**Comment by jstrachan** [comment]
great catch - I was just starting to try figure this out and I saw your other PR fly by thanks! :)

**Comment by rhuss** [comment]
Don't think its an issue anymore.
